// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type FirewallConsolidatedPolicy struct {
	pulumi.CustomResourceState

	Action                         pulumi.StringOutput                                                `pulumi:"action"`
	AppCategories                  FirewallConsolidatedPolicyAppCategoryArrayOutput                   `pulumi:"appCategories"`
	AppGroups                      FirewallConsolidatedPolicyAppGroupArrayOutput                      `pulumi:"appGroups"`
	ApplicationList                pulumi.StringOutput                                                `pulumi:"applicationList"`
	Applications                   FirewallConsolidatedPolicyApplicationArrayOutput                   `pulumi:"applications"`
	AutoAsicOffload                pulumi.StringOutput                                                `pulumi:"autoAsicOffload"`
	AvProfile                      pulumi.StringOutput                                                `pulumi:"avProfile"`
	CaptivePortalExempt            pulumi.StringOutput                                                `pulumi:"captivePortalExempt"`
	CifsProfile                    pulumi.StringOutput                                                `pulumi:"cifsProfile"`
	Comments                       pulumi.StringPtrOutput                                             `pulumi:"comments"`
	DiffservForward                pulumi.StringOutput                                                `pulumi:"diffservForward"`
	DiffservReverse                pulumi.StringOutput                                                `pulumi:"diffservReverse"`
	DiffservcodeForward            pulumi.StringOutput                                                `pulumi:"diffservcodeForward"`
	DiffservcodeRev                pulumi.StringOutput                                                `pulumi:"diffservcodeRev"`
	DlpSensor                      pulumi.StringOutput                                                `pulumi:"dlpSensor"`
	DnsfilterProfile               pulumi.StringOutput                                                `pulumi:"dnsfilterProfile"`
	Dstaddr4s                      FirewallConsolidatedPolicyDstaddr4ArrayOutput                      `pulumi:"dstaddr4s"`
	Dstaddr6s                      FirewallConsolidatedPolicyDstaddr6ArrayOutput                      `pulumi:"dstaddr6s"`
	DstaddrNegate                  pulumi.StringOutput                                                `pulumi:"dstaddrNegate"`
	Dstintfs                       FirewallConsolidatedPolicyDstintfArrayOutput                       `pulumi:"dstintfs"`
	DynamicSortSubtable            pulumi.StringPtrOutput                                             `pulumi:"dynamicSortSubtable"`
	EmailfilterProfile             pulumi.StringOutput                                                `pulumi:"emailfilterProfile"`
	Fixedport                      pulumi.StringOutput                                                `pulumi:"fixedport"`
	FssoGroups                     FirewallConsolidatedPolicyFssoGroupArrayOutput                     `pulumi:"fssoGroups"`
	Groups                         FirewallConsolidatedPolicyGroupArrayOutput                         `pulumi:"groups"`
	HttpPolicyRedirect             pulumi.StringOutput                                                `pulumi:"httpPolicyRedirect"`
	IcapProfile                    pulumi.StringOutput                                                `pulumi:"icapProfile"`
	Inbound                        pulumi.StringOutput                                                `pulumi:"inbound"`
	InspectionMode                 pulumi.StringOutput                                                `pulumi:"inspectionMode"`
	InternetService                pulumi.StringOutput                                                `pulumi:"internetService"`
	InternetServiceCustomGroups    FirewallConsolidatedPolicyInternetServiceCustomGroupArrayOutput    `pulumi:"internetServiceCustomGroups"`
	InternetServiceCustoms         FirewallConsolidatedPolicyInternetServiceCustomArrayOutput         `pulumi:"internetServiceCustoms"`
	InternetServiceGroups          FirewallConsolidatedPolicyInternetServiceGroupArrayOutput          `pulumi:"internetServiceGroups"`
	InternetServiceIds             FirewallConsolidatedPolicyInternetServiceIdArrayOutput             `pulumi:"internetServiceIds"`
	InternetServiceNames           FirewallConsolidatedPolicyInternetServiceNameArrayOutput           `pulumi:"internetServiceNames"`
	InternetServiceNegate          pulumi.StringOutput                                                `pulumi:"internetServiceNegate"`
	InternetServiceSrc             pulumi.StringOutput                                                `pulumi:"internetServiceSrc"`
	InternetServiceSrcCustomGroups FirewallConsolidatedPolicyInternetServiceSrcCustomGroupArrayOutput `pulumi:"internetServiceSrcCustomGroups"`
	InternetServiceSrcCustoms      FirewallConsolidatedPolicyInternetServiceSrcCustomArrayOutput      `pulumi:"internetServiceSrcCustoms"`
	InternetServiceSrcGroups       FirewallConsolidatedPolicyInternetServiceSrcGroupArrayOutput       `pulumi:"internetServiceSrcGroups"`
	InternetServiceSrcIds          FirewallConsolidatedPolicyInternetServiceSrcIdArrayOutput          `pulumi:"internetServiceSrcIds"`
	InternetServiceSrcNames        FirewallConsolidatedPolicyInternetServiceSrcNameArrayOutput        `pulumi:"internetServiceSrcNames"`
	InternetServiceSrcNegate       pulumi.StringOutput                                                `pulumi:"internetServiceSrcNegate"`
	Ippool                         pulumi.StringOutput                                                `pulumi:"ippool"`
	IpsSensor                      pulumi.StringOutput                                                `pulumi:"ipsSensor"`
	Logtraffic                     pulumi.StringOutput                                                `pulumi:"logtraffic"`
	LogtrafficStart                pulumi.StringOutput                                                `pulumi:"logtrafficStart"`
	Name                           pulumi.StringOutput                                                `pulumi:"name"`
	Nat                            pulumi.StringOutput                                                `pulumi:"nat"`
	Outbound                       pulumi.StringOutput                                                `pulumi:"outbound"`
	PerIpShaper                    pulumi.StringOutput                                                `pulumi:"perIpShaper"`
	Policyid                       pulumi.IntOutput                                                   `pulumi:"policyid"`
	Poolname4s                     FirewallConsolidatedPolicyPoolname4ArrayOutput                     `pulumi:"poolname4s"`
	Poolname6s                     FirewallConsolidatedPolicyPoolname6ArrayOutput                     `pulumi:"poolname6s"`
	ProfileGroup                   pulumi.StringOutput                                                `pulumi:"profileGroup"`
	ProfileProtocolOptions         pulumi.StringOutput                                                `pulumi:"profileProtocolOptions"`
	ProfileType                    pulumi.StringOutput                                                `pulumi:"profileType"`
	Schedule                       pulumi.StringOutput                                                `pulumi:"schedule"`
	ServiceNegate                  pulumi.StringOutput                                                `pulumi:"serviceNegate"`
	Services                       FirewallConsolidatedPolicyServiceArrayOutput                       `pulumi:"services"`
	SessionTtl                     pulumi.IntOutput                                                   `pulumi:"sessionTtl"`
	SpamfilterProfile              pulumi.StringOutput                                                `pulumi:"spamfilterProfile"`
	Srcaddr4s                      FirewallConsolidatedPolicySrcaddr4ArrayOutput                      `pulumi:"srcaddr4s"`
	Srcaddr6s                      FirewallConsolidatedPolicySrcaddr6ArrayOutput                      `pulumi:"srcaddr6s"`
	SrcaddrNegate                  pulumi.StringOutput                                                `pulumi:"srcaddrNegate"`
	Srcintfs                       FirewallConsolidatedPolicySrcintfArrayOutput                       `pulumi:"srcintfs"`
	SshFilterProfile               pulumi.StringOutput                                                `pulumi:"sshFilterProfile"`
	SshPolicyRedirect              pulumi.StringOutput                                                `pulumi:"sshPolicyRedirect"`
	SslSshProfile                  pulumi.StringOutput                                                `pulumi:"sslSshProfile"`
	Status                         pulumi.StringOutput                                                `pulumi:"status"`
	TcpMssReceiver                 pulumi.IntOutput                                                   `pulumi:"tcpMssReceiver"`
	TcpMssSender                   pulumi.IntOutput                                                   `pulumi:"tcpMssSender"`
	TrafficShaper                  pulumi.StringOutput                                                `pulumi:"trafficShaper"`
	TrafficShaperReverse           pulumi.StringOutput                                                `pulumi:"trafficShaperReverse"`
	UrlCategories                  FirewallConsolidatedPolicyUrlCategoryArrayOutput                   `pulumi:"urlCategories"`
	Users                          FirewallConsolidatedPolicyUserArrayOutput                          `pulumi:"users"`
	UtmStatus                      pulumi.StringOutput                                                `pulumi:"utmStatus"`
	Uuid                           pulumi.StringOutput                                                `pulumi:"uuid"`
	Vdomparam                      pulumi.StringPtrOutput                                             `pulumi:"vdomparam"`
	VoipProfile                    pulumi.StringOutput                                                `pulumi:"voipProfile"`
	Vpntunnel                      pulumi.StringOutput                                                `pulumi:"vpntunnel"`
	WafProfile                     pulumi.StringOutput                                                `pulumi:"wafProfile"`
	Wanopt                         pulumi.StringOutput                                                `pulumi:"wanopt"`
	WanoptDetection                pulumi.StringOutput                                                `pulumi:"wanoptDetection"`
	WanoptPassiveOpt               pulumi.StringOutput                                                `pulumi:"wanoptPassiveOpt"`
	WanoptPeer                     pulumi.StringOutput                                                `pulumi:"wanoptPeer"`
	WanoptProfile                  pulumi.StringOutput                                                `pulumi:"wanoptProfile"`
	Webcache                       pulumi.StringOutput                                                `pulumi:"webcache"`
	WebcacheHttps                  pulumi.StringOutput                                                `pulumi:"webcacheHttps"`
	WebfilterProfile               pulumi.StringOutput                                                `pulumi:"webfilterProfile"`
	WebproxyForwardServer          pulumi.StringOutput                                                `pulumi:"webproxyForwardServer"`
	WebproxyProfile                pulumi.StringOutput                                                `pulumi:"webproxyProfile"`
}

// NewFirewallConsolidatedPolicy registers a new resource with the given unique name, arguments, and options.
func NewFirewallConsolidatedPolicy(ctx *pulumi.Context,
	name string, args *FirewallConsolidatedPolicyArgs, opts ...pulumi.ResourceOption) (*FirewallConsolidatedPolicy, error) {
	if args == nil {
		args = &FirewallConsolidatedPolicyArgs{}
	}

	opts = pkgResourceDefaultOpts(opts)
	var resource FirewallConsolidatedPolicy
	err := ctx.RegisterResource("fortios:index/firewallConsolidatedPolicy:FirewallConsolidatedPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFirewallConsolidatedPolicy gets an existing FirewallConsolidatedPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFirewallConsolidatedPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FirewallConsolidatedPolicyState, opts ...pulumi.ResourceOption) (*FirewallConsolidatedPolicy, error) {
	var resource FirewallConsolidatedPolicy
	err := ctx.ReadResource("fortios:index/firewallConsolidatedPolicy:FirewallConsolidatedPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FirewallConsolidatedPolicy resources.
type firewallConsolidatedPolicyState struct {
	Action                         *string                                                   `pulumi:"action"`
	AppCategories                  []FirewallConsolidatedPolicyAppCategory                   `pulumi:"appCategories"`
	AppGroups                      []FirewallConsolidatedPolicyAppGroup                      `pulumi:"appGroups"`
	ApplicationList                *string                                                   `pulumi:"applicationList"`
	Applications                   []FirewallConsolidatedPolicyApplication                   `pulumi:"applications"`
	AutoAsicOffload                *string                                                   `pulumi:"autoAsicOffload"`
	AvProfile                      *string                                                   `pulumi:"avProfile"`
	CaptivePortalExempt            *string                                                   `pulumi:"captivePortalExempt"`
	CifsProfile                    *string                                                   `pulumi:"cifsProfile"`
	Comments                       *string                                                   `pulumi:"comments"`
	DiffservForward                *string                                                   `pulumi:"diffservForward"`
	DiffservReverse                *string                                                   `pulumi:"diffservReverse"`
	DiffservcodeForward            *string                                                   `pulumi:"diffservcodeForward"`
	DiffservcodeRev                *string                                                   `pulumi:"diffservcodeRev"`
	DlpSensor                      *string                                                   `pulumi:"dlpSensor"`
	DnsfilterProfile               *string                                                   `pulumi:"dnsfilterProfile"`
	Dstaddr4s                      []FirewallConsolidatedPolicyDstaddr4                      `pulumi:"dstaddr4s"`
	Dstaddr6s                      []FirewallConsolidatedPolicyDstaddr6                      `pulumi:"dstaddr6s"`
	DstaddrNegate                  *string                                                   `pulumi:"dstaddrNegate"`
	Dstintfs                       []FirewallConsolidatedPolicyDstintf                       `pulumi:"dstintfs"`
	DynamicSortSubtable            *string                                                   `pulumi:"dynamicSortSubtable"`
	EmailfilterProfile             *string                                                   `pulumi:"emailfilterProfile"`
	Fixedport                      *string                                                   `pulumi:"fixedport"`
	FssoGroups                     []FirewallConsolidatedPolicyFssoGroup                     `pulumi:"fssoGroups"`
	Groups                         []FirewallConsolidatedPolicyGroup                         `pulumi:"groups"`
	HttpPolicyRedirect             *string                                                   `pulumi:"httpPolicyRedirect"`
	IcapProfile                    *string                                                   `pulumi:"icapProfile"`
	Inbound                        *string                                                   `pulumi:"inbound"`
	InspectionMode                 *string                                                   `pulumi:"inspectionMode"`
	InternetService                *string                                                   `pulumi:"internetService"`
	InternetServiceCustomGroups    []FirewallConsolidatedPolicyInternetServiceCustomGroup    `pulumi:"internetServiceCustomGroups"`
	InternetServiceCustoms         []FirewallConsolidatedPolicyInternetServiceCustom         `pulumi:"internetServiceCustoms"`
	InternetServiceGroups          []FirewallConsolidatedPolicyInternetServiceGroup          `pulumi:"internetServiceGroups"`
	InternetServiceIds             []FirewallConsolidatedPolicyInternetServiceId             `pulumi:"internetServiceIds"`
	InternetServiceNames           []FirewallConsolidatedPolicyInternetServiceName           `pulumi:"internetServiceNames"`
	InternetServiceNegate          *string                                                   `pulumi:"internetServiceNegate"`
	InternetServiceSrc             *string                                                   `pulumi:"internetServiceSrc"`
	InternetServiceSrcCustomGroups []FirewallConsolidatedPolicyInternetServiceSrcCustomGroup `pulumi:"internetServiceSrcCustomGroups"`
	InternetServiceSrcCustoms      []FirewallConsolidatedPolicyInternetServiceSrcCustom      `pulumi:"internetServiceSrcCustoms"`
	InternetServiceSrcGroups       []FirewallConsolidatedPolicyInternetServiceSrcGroup       `pulumi:"internetServiceSrcGroups"`
	InternetServiceSrcIds          []FirewallConsolidatedPolicyInternetServiceSrcId          `pulumi:"internetServiceSrcIds"`
	InternetServiceSrcNames        []FirewallConsolidatedPolicyInternetServiceSrcName        `pulumi:"internetServiceSrcNames"`
	InternetServiceSrcNegate       *string                                                   `pulumi:"internetServiceSrcNegate"`
	Ippool                         *string                                                   `pulumi:"ippool"`
	IpsSensor                      *string                                                   `pulumi:"ipsSensor"`
	Logtraffic                     *string                                                   `pulumi:"logtraffic"`
	LogtrafficStart                *string                                                   `pulumi:"logtrafficStart"`
	Name                           *string                                                   `pulumi:"name"`
	Nat                            *string                                                   `pulumi:"nat"`
	Outbound                       *string                                                   `pulumi:"outbound"`
	PerIpShaper                    *string                                                   `pulumi:"perIpShaper"`
	Policyid                       *int                                                      `pulumi:"policyid"`
	Poolname4s                     []FirewallConsolidatedPolicyPoolname4                     `pulumi:"poolname4s"`
	Poolname6s                     []FirewallConsolidatedPolicyPoolname6                     `pulumi:"poolname6s"`
	ProfileGroup                   *string                                                   `pulumi:"profileGroup"`
	ProfileProtocolOptions         *string                                                   `pulumi:"profileProtocolOptions"`
	ProfileType                    *string                                                   `pulumi:"profileType"`
	Schedule                       *string                                                   `pulumi:"schedule"`
	ServiceNegate                  *string                                                   `pulumi:"serviceNegate"`
	Services                       []FirewallConsolidatedPolicyService                       `pulumi:"services"`
	SessionTtl                     *int                                                      `pulumi:"sessionTtl"`
	SpamfilterProfile              *string                                                   `pulumi:"spamfilterProfile"`
	Srcaddr4s                      []FirewallConsolidatedPolicySrcaddr4                      `pulumi:"srcaddr4s"`
	Srcaddr6s                      []FirewallConsolidatedPolicySrcaddr6                      `pulumi:"srcaddr6s"`
	SrcaddrNegate                  *string                                                   `pulumi:"srcaddrNegate"`
	Srcintfs                       []FirewallConsolidatedPolicySrcintf                       `pulumi:"srcintfs"`
	SshFilterProfile               *string                                                   `pulumi:"sshFilterProfile"`
	SshPolicyRedirect              *string                                                   `pulumi:"sshPolicyRedirect"`
	SslSshProfile                  *string                                                   `pulumi:"sslSshProfile"`
	Status                         *string                                                   `pulumi:"status"`
	TcpMssReceiver                 *int                                                      `pulumi:"tcpMssReceiver"`
	TcpMssSender                   *int                                                      `pulumi:"tcpMssSender"`
	TrafficShaper                  *string                                                   `pulumi:"trafficShaper"`
	TrafficShaperReverse           *string                                                   `pulumi:"trafficShaperReverse"`
	UrlCategories                  []FirewallConsolidatedPolicyUrlCategory                   `pulumi:"urlCategories"`
	Users                          []FirewallConsolidatedPolicyUser                          `pulumi:"users"`
	UtmStatus                      *string                                                   `pulumi:"utmStatus"`
	Uuid                           *string                                                   `pulumi:"uuid"`
	Vdomparam                      *string                                                   `pulumi:"vdomparam"`
	VoipProfile                    *string                                                   `pulumi:"voipProfile"`
	Vpntunnel                      *string                                                   `pulumi:"vpntunnel"`
	WafProfile                     *string                                                   `pulumi:"wafProfile"`
	Wanopt                         *string                                                   `pulumi:"wanopt"`
	WanoptDetection                *string                                                   `pulumi:"wanoptDetection"`
	WanoptPassiveOpt               *string                                                   `pulumi:"wanoptPassiveOpt"`
	WanoptPeer                     *string                                                   `pulumi:"wanoptPeer"`
	WanoptProfile                  *string                                                   `pulumi:"wanoptProfile"`
	Webcache                       *string                                                   `pulumi:"webcache"`
	WebcacheHttps                  *string                                                   `pulumi:"webcacheHttps"`
	WebfilterProfile               *string                                                   `pulumi:"webfilterProfile"`
	WebproxyForwardServer          *string                                                   `pulumi:"webproxyForwardServer"`
	WebproxyProfile                *string                                                   `pulumi:"webproxyProfile"`
}

type FirewallConsolidatedPolicyState struct {
	Action                         pulumi.StringPtrInput
	AppCategories                  FirewallConsolidatedPolicyAppCategoryArrayInput
	AppGroups                      FirewallConsolidatedPolicyAppGroupArrayInput
	ApplicationList                pulumi.StringPtrInput
	Applications                   FirewallConsolidatedPolicyApplicationArrayInput
	AutoAsicOffload                pulumi.StringPtrInput
	AvProfile                      pulumi.StringPtrInput
	CaptivePortalExempt            pulumi.StringPtrInput
	CifsProfile                    pulumi.StringPtrInput
	Comments                       pulumi.StringPtrInput
	DiffservForward                pulumi.StringPtrInput
	DiffservReverse                pulumi.StringPtrInput
	DiffservcodeForward            pulumi.StringPtrInput
	DiffservcodeRev                pulumi.StringPtrInput
	DlpSensor                      pulumi.StringPtrInput
	DnsfilterProfile               pulumi.StringPtrInput
	Dstaddr4s                      FirewallConsolidatedPolicyDstaddr4ArrayInput
	Dstaddr6s                      FirewallConsolidatedPolicyDstaddr6ArrayInput
	DstaddrNegate                  pulumi.StringPtrInput
	Dstintfs                       FirewallConsolidatedPolicyDstintfArrayInput
	DynamicSortSubtable            pulumi.StringPtrInput
	EmailfilterProfile             pulumi.StringPtrInput
	Fixedport                      pulumi.StringPtrInput
	FssoGroups                     FirewallConsolidatedPolicyFssoGroupArrayInput
	Groups                         FirewallConsolidatedPolicyGroupArrayInput
	HttpPolicyRedirect             pulumi.StringPtrInput
	IcapProfile                    pulumi.StringPtrInput
	Inbound                        pulumi.StringPtrInput
	InspectionMode                 pulumi.StringPtrInput
	InternetService                pulumi.StringPtrInput
	InternetServiceCustomGroups    FirewallConsolidatedPolicyInternetServiceCustomGroupArrayInput
	InternetServiceCustoms         FirewallConsolidatedPolicyInternetServiceCustomArrayInput
	InternetServiceGroups          FirewallConsolidatedPolicyInternetServiceGroupArrayInput
	InternetServiceIds             FirewallConsolidatedPolicyInternetServiceIdArrayInput
	InternetServiceNames           FirewallConsolidatedPolicyInternetServiceNameArrayInput
	InternetServiceNegate          pulumi.StringPtrInput
	InternetServiceSrc             pulumi.StringPtrInput
	InternetServiceSrcCustomGroups FirewallConsolidatedPolicyInternetServiceSrcCustomGroupArrayInput
	InternetServiceSrcCustoms      FirewallConsolidatedPolicyInternetServiceSrcCustomArrayInput
	InternetServiceSrcGroups       FirewallConsolidatedPolicyInternetServiceSrcGroupArrayInput
	InternetServiceSrcIds          FirewallConsolidatedPolicyInternetServiceSrcIdArrayInput
	InternetServiceSrcNames        FirewallConsolidatedPolicyInternetServiceSrcNameArrayInput
	InternetServiceSrcNegate       pulumi.StringPtrInput
	Ippool                         pulumi.StringPtrInput
	IpsSensor                      pulumi.StringPtrInput
	Logtraffic                     pulumi.StringPtrInput
	LogtrafficStart                pulumi.StringPtrInput
	Name                           pulumi.StringPtrInput
	Nat                            pulumi.StringPtrInput
	Outbound                       pulumi.StringPtrInput
	PerIpShaper                    pulumi.StringPtrInput
	Policyid                       pulumi.IntPtrInput
	Poolname4s                     FirewallConsolidatedPolicyPoolname4ArrayInput
	Poolname6s                     FirewallConsolidatedPolicyPoolname6ArrayInput
	ProfileGroup                   pulumi.StringPtrInput
	ProfileProtocolOptions         pulumi.StringPtrInput
	ProfileType                    pulumi.StringPtrInput
	Schedule                       pulumi.StringPtrInput
	ServiceNegate                  pulumi.StringPtrInput
	Services                       FirewallConsolidatedPolicyServiceArrayInput
	SessionTtl                     pulumi.IntPtrInput
	SpamfilterProfile              pulumi.StringPtrInput
	Srcaddr4s                      FirewallConsolidatedPolicySrcaddr4ArrayInput
	Srcaddr6s                      FirewallConsolidatedPolicySrcaddr6ArrayInput
	SrcaddrNegate                  pulumi.StringPtrInput
	Srcintfs                       FirewallConsolidatedPolicySrcintfArrayInput
	SshFilterProfile               pulumi.StringPtrInput
	SshPolicyRedirect              pulumi.StringPtrInput
	SslSshProfile                  pulumi.StringPtrInput
	Status                         pulumi.StringPtrInput
	TcpMssReceiver                 pulumi.IntPtrInput
	TcpMssSender                   pulumi.IntPtrInput
	TrafficShaper                  pulumi.StringPtrInput
	TrafficShaperReverse           pulumi.StringPtrInput
	UrlCategories                  FirewallConsolidatedPolicyUrlCategoryArrayInput
	Users                          FirewallConsolidatedPolicyUserArrayInput
	UtmStatus                      pulumi.StringPtrInput
	Uuid                           pulumi.StringPtrInput
	Vdomparam                      pulumi.StringPtrInput
	VoipProfile                    pulumi.StringPtrInput
	Vpntunnel                      pulumi.StringPtrInput
	WafProfile                     pulumi.StringPtrInput
	Wanopt                         pulumi.StringPtrInput
	WanoptDetection                pulumi.StringPtrInput
	WanoptPassiveOpt               pulumi.StringPtrInput
	WanoptPeer                     pulumi.StringPtrInput
	WanoptProfile                  pulumi.StringPtrInput
	Webcache                       pulumi.StringPtrInput
	WebcacheHttps                  pulumi.StringPtrInput
	WebfilterProfile               pulumi.StringPtrInput
	WebproxyForwardServer          pulumi.StringPtrInput
	WebproxyProfile                pulumi.StringPtrInput
}

func (FirewallConsolidatedPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*firewallConsolidatedPolicyState)(nil)).Elem()
}

type firewallConsolidatedPolicyArgs struct {
	Action                         *string                                                   `pulumi:"action"`
	AppCategories                  []FirewallConsolidatedPolicyAppCategory                   `pulumi:"appCategories"`
	AppGroups                      []FirewallConsolidatedPolicyAppGroup                      `pulumi:"appGroups"`
	ApplicationList                *string                                                   `pulumi:"applicationList"`
	Applications                   []FirewallConsolidatedPolicyApplication                   `pulumi:"applications"`
	AutoAsicOffload                *string                                                   `pulumi:"autoAsicOffload"`
	AvProfile                      *string                                                   `pulumi:"avProfile"`
	CaptivePortalExempt            *string                                                   `pulumi:"captivePortalExempt"`
	CifsProfile                    *string                                                   `pulumi:"cifsProfile"`
	Comments                       *string                                                   `pulumi:"comments"`
	DiffservForward                *string                                                   `pulumi:"diffservForward"`
	DiffservReverse                *string                                                   `pulumi:"diffservReverse"`
	DiffservcodeForward            *string                                                   `pulumi:"diffservcodeForward"`
	DiffservcodeRev                *string                                                   `pulumi:"diffservcodeRev"`
	DlpSensor                      *string                                                   `pulumi:"dlpSensor"`
	DnsfilterProfile               *string                                                   `pulumi:"dnsfilterProfile"`
	Dstaddr4s                      []FirewallConsolidatedPolicyDstaddr4                      `pulumi:"dstaddr4s"`
	Dstaddr6s                      []FirewallConsolidatedPolicyDstaddr6                      `pulumi:"dstaddr6s"`
	DstaddrNegate                  *string                                                   `pulumi:"dstaddrNegate"`
	Dstintfs                       []FirewallConsolidatedPolicyDstintf                       `pulumi:"dstintfs"`
	DynamicSortSubtable            *string                                                   `pulumi:"dynamicSortSubtable"`
	EmailfilterProfile             *string                                                   `pulumi:"emailfilterProfile"`
	Fixedport                      *string                                                   `pulumi:"fixedport"`
	FssoGroups                     []FirewallConsolidatedPolicyFssoGroup                     `pulumi:"fssoGroups"`
	Groups                         []FirewallConsolidatedPolicyGroup                         `pulumi:"groups"`
	HttpPolicyRedirect             *string                                                   `pulumi:"httpPolicyRedirect"`
	IcapProfile                    *string                                                   `pulumi:"icapProfile"`
	Inbound                        *string                                                   `pulumi:"inbound"`
	InspectionMode                 *string                                                   `pulumi:"inspectionMode"`
	InternetService                *string                                                   `pulumi:"internetService"`
	InternetServiceCustomGroups    []FirewallConsolidatedPolicyInternetServiceCustomGroup    `pulumi:"internetServiceCustomGroups"`
	InternetServiceCustoms         []FirewallConsolidatedPolicyInternetServiceCustom         `pulumi:"internetServiceCustoms"`
	InternetServiceGroups          []FirewallConsolidatedPolicyInternetServiceGroup          `pulumi:"internetServiceGroups"`
	InternetServiceIds             []FirewallConsolidatedPolicyInternetServiceId             `pulumi:"internetServiceIds"`
	InternetServiceNames           []FirewallConsolidatedPolicyInternetServiceName           `pulumi:"internetServiceNames"`
	InternetServiceNegate          *string                                                   `pulumi:"internetServiceNegate"`
	InternetServiceSrc             *string                                                   `pulumi:"internetServiceSrc"`
	InternetServiceSrcCustomGroups []FirewallConsolidatedPolicyInternetServiceSrcCustomGroup `pulumi:"internetServiceSrcCustomGroups"`
	InternetServiceSrcCustoms      []FirewallConsolidatedPolicyInternetServiceSrcCustom      `pulumi:"internetServiceSrcCustoms"`
	InternetServiceSrcGroups       []FirewallConsolidatedPolicyInternetServiceSrcGroup       `pulumi:"internetServiceSrcGroups"`
	InternetServiceSrcIds          []FirewallConsolidatedPolicyInternetServiceSrcId          `pulumi:"internetServiceSrcIds"`
	InternetServiceSrcNames        []FirewallConsolidatedPolicyInternetServiceSrcName        `pulumi:"internetServiceSrcNames"`
	InternetServiceSrcNegate       *string                                                   `pulumi:"internetServiceSrcNegate"`
	Ippool                         *string                                                   `pulumi:"ippool"`
	IpsSensor                      *string                                                   `pulumi:"ipsSensor"`
	Logtraffic                     *string                                                   `pulumi:"logtraffic"`
	LogtrafficStart                *string                                                   `pulumi:"logtrafficStart"`
	Name                           *string                                                   `pulumi:"name"`
	Nat                            *string                                                   `pulumi:"nat"`
	Outbound                       *string                                                   `pulumi:"outbound"`
	PerIpShaper                    *string                                                   `pulumi:"perIpShaper"`
	Policyid                       *int                                                      `pulumi:"policyid"`
	Poolname4s                     []FirewallConsolidatedPolicyPoolname4                     `pulumi:"poolname4s"`
	Poolname6s                     []FirewallConsolidatedPolicyPoolname6                     `pulumi:"poolname6s"`
	ProfileGroup                   *string                                                   `pulumi:"profileGroup"`
	ProfileProtocolOptions         *string                                                   `pulumi:"profileProtocolOptions"`
	ProfileType                    *string                                                   `pulumi:"profileType"`
	Schedule                       *string                                                   `pulumi:"schedule"`
	ServiceNegate                  *string                                                   `pulumi:"serviceNegate"`
	Services                       []FirewallConsolidatedPolicyService                       `pulumi:"services"`
	SessionTtl                     *int                                                      `pulumi:"sessionTtl"`
	SpamfilterProfile              *string                                                   `pulumi:"spamfilterProfile"`
	Srcaddr4s                      []FirewallConsolidatedPolicySrcaddr4                      `pulumi:"srcaddr4s"`
	Srcaddr6s                      []FirewallConsolidatedPolicySrcaddr6                      `pulumi:"srcaddr6s"`
	SrcaddrNegate                  *string                                                   `pulumi:"srcaddrNegate"`
	Srcintfs                       []FirewallConsolidatedPolicySrcintf                       `pulumi:"srcintfs"`
	SshFilterProfile               *string                                                   `pulumi:"sshFilterProfile"`
	SshPolicyRedirect              *string                                                   `pulumi:"sshPolicyRedirect"`
	SslSshProfile                  *string                                                   `pulumi:"sslSshProfile"`
	Status                         *string                                                   `pulumi:"status"`
	TcpMssReceiver                 *int                                                      `pulumi:"tcpMssReceiver"`
	TcpMssSender                   *int                                                      `pulumi:"tcpMssSender"`
	TrafficShaper                  *string                                                   `pulumi:"trafficShaper"`
	TrafficShaperReverse           *string                                                   `pulumi:"trafficShaperReverse"`
	UrlCategories                  []FirewallConsolidatedPolicyUrlCategory                   `pulumi:"urlCategories"`
	Users                          []FirewallConsolidatedPolicyUser                          `pulumi:"users"`
	UtmStatus                      *string                                                   `pulumi:"utmStatus"`
	Uuid                           *string                                                   `pulumi:"uuid"`
	Vdomparam                      *string                                                   `pulumi:"vdomparam"`
	VoipProfile                    *string                                                   `pulumi:"voipProfile"`
	Vpntunnel                      *string                                                   `pulumi:"vpntunnel"`
	WafProfile                     *string                                                   `pulumi:"wafProfile"`
	Wanopt                         *string                                                   `pulumi:"wanopt"`
	WanoptDetection                *string                                                   `pulumi:"wanoptDetection"`
	WanoptPassiveOpt               *string                                                   `pulumi:"wanoptPassiveOpt"`
	WanoptPeer                     *string                                                   `pulumi:"wanoptPeer"`
	WanoptProfile                  *string                                                   `pulumi:"wanoptProfile"`
	Webcache                       *string                                                   `pulumi:"webcache"`
	WebcacheHttps                  *string                                                   `pulumi:"webcacheHttps"`
	WebfilterProfile               *string                                                   `pulumi:"webfilterProfile"`
	WebproxyForwardServer          *string                                                   `pulumi:"webproxyForwardServer"`
	WebproxyProfile                *string                                                   `pulumi:"webproxyProfile"`
}

// The set of arguments for constructing a FirewallConsolidatedPolicy resource.
type FirewallConsolidatedPolicyArgs struct {
	Action                         pulumi.StringPtrInput
	AppCategories                  FirewallConsolidatedPolicyAppCategoryArrayInput
	AppGroups                      FirewallConsolidatedPolicyAppGroupArrayInput
	ApplicationList                pulumi.StringPtrInput
	Applications                   FirewallConsolidatedPolicyApplicationArrayInput
	AutoAsicOffload                pulumi.StringPtrInput
	AvProfile                      pulumi.StringPtrInput
	CaptivePortalExempt            pulumi.StringPtrInput
	CifsProfile                    pulumi.StringPtrInput
	Comments                       pulumi.StringPtrInput
	DiffservForward                pulumi.StringPtrInput
	DiffservReverse                pulumi.StringPtrInput
	DiffservcodeForward            pulumi.StringPtrInput
	DiffservcodeRev                pulumi.StringPtrInput
	DlpSensor                      pulumi.StringPtrInput
	DnsfilterProfile               pulumi.StringPtrInput
	Dstaddr4s                      FirewallConsolidatedPolicyDstaddr4ArrayInput
	Dstaddr6s                      FirewallConsolidatedPolicyDstaddr6ArrayInput
	DstaddrNegate                  pulumi.StringPtrInput
	Dstintfs                       FirewallConsolidatedPolicyDstintfArrayInput
	DynamicSortSubtable            pulumi.StringPtrInput
	EmailfilterProfile             pulumi.StringPtrInput
	Fixedport                      pulumi.StringPtrInput
	FssoGroups                     FirewallConsolidatedPolicyFssoGroupArrayInput
	Groups                         FirewallConsolidatedPolicyGroupArrayInput
	HttpPolicyRedirect             pulumi.StringPtrInput
	IcapProfile                    pulumi.StringPtrInput
	Inbound                        pulumi.StringPtrInput
	InspectionMode                 pulumi.StringPtrInput
	InternetService                pulumi.StringPtrInput
	InternetServiceCustomGroups    FirewallConsolidatedPolicyInternetServiceCustomGroupArrayInput
	InternetServiceCustoms         FirewallConsolidatedPolicyInternetServiceCustomArrayInput
	InternetServiceGroups          FirewallConsolidatedPolicyInternetServiceGroupArrayInput
	InternetServiceIds             FirewallConsolidatedPolicyInternetServiceIdArrayInput
	InternetServiceNames           FirewallConsolidatedPolicyInternetServiceNameArrayInput
	InternetServiceNegate          pulumi.StringPtrInput
	InternetServiceSrc             pulumi.StringPtrInput
	InternetServiceSrcCustomGroups FirewallConsolidatedPolicyInternetServiceSrcCustomGroupArrayInput
	InternetServiceSrcCustoms      FirewallConsolidatedPolicyInternetServiceSrcCustomArrayInput
	InternetServiceSrcGroups       FirewallConsolidatedPolicyInternetServiceSrcGroupArrayInput
	InternetServiceSrcIds          FirewallConsolidatedPolicyInternetServiceSrcIdArrayInput
	InternetServiceSrcNames        FirewallConsolidatedPolicyInternetServiceSrcNameArrayInput
	InternetServiceSrcNegate       pulumi.StringPtrInput
	Ippool                         pulumi.StringPtrInput
	IpsSensor                      pulumi.StringPtrInput
	Logtraffic                     pulumi.StringPtrInput
	LogtrafficStart                pulumi.StringPtrInput
	Name                           pulumi.StringPtrInput
	Nat                            pulumi.StringPtrInput
	Outbound                       pulumi.StringPtrInput
	PerIpShaper                    pulumi.StringPtrInput
	Policyid                       pulumi.IntPtrInput
	Poolname4s                     FirewallConsolidatedPolicyPoolname4ArrayInput
	Poolname6s                     FirewallConsolidatedPolicyPoolname6ArrayInput
	ProfileGroup                   pulumi.StringPtrInput
	ProfileProtocolOptions         pulumi.StringPtrInput
	ProfileType                    pulumi.StringPtrInput
	Schedule                       pulumi.StringPtrInput
	ServiceNegate                  pulumi.StringPtrInput
	Services                       FirewallConsolidatedPolicyServiceArrayInput
	SessionTtl                     pulumi.IntPtrInput
	SpamfilterProfile              pulumi.StringPtrInput
	Srcaddr4s                      FirewallConsolidatedPolicySrcaddr4ArrayInput
	Srcaddr6s                      FirewallConsolidatedPolicySrcaddr6ArrayInput
	SrcaddrNegate                  pulumi.StringPtrInput
	Srcintfs                       FirewallConsolidatedPolicySrcintfArrayInput
	SshFilterProfile               pulumi.StringPtrInput
	SshPolicyRedirect              pulumi.StringPtrInput
	SslSshProfile                  pulumi.StringPtrInput
	Status                         pulumi.StringPtrInput
	TcpMssReceiver                 pulumi.IntPtrInput
	TcpMssSender                   pulumi.IntPtrInput
	TrafficShaper                  pulumi.StringPtrInput
	TrafficShaperReverse           pulumi.StringPtrInput
	UrlCategories                  FirewallConsolidatedPolicyUrlCategoryArrayInput
	Users                          FirewallConsolidatedPolicyUserArrayInput
	UtmStatus                      pulumi.StringPtrInput
	Uuid                           pulumi.StringPtrInput
	Vdomparam                      pulumi.StringPtrInput
	VoipProfile                    pulumi.StringPtrInput
	Vpntunnel                      pulumi.StringPtrInput
	WafProfile                     pulumi.StringPtrInput
	Wanopt                         pulumi.StringPtrInput
	WanoptDetection                pulumi.StringPtrInput
	WanoptPassiveOpt               pulumi.StringPtrInput
	WanoptPeer                     pulumi.StringPtrInput
	WanoptProfile                  pulumi.StringPtrInput
	Webcache                       pulumi.StringPtrInput
	WebcacheHttps                  pulumi.StringPtrInput
	WebfilterProfile               pulumi.StringPtrInput
	WebproxyForwardServer          pulumi.StringPtrInput
	WebproxyProfile                pulumi.StringPtrInput
}

func (FirewallConsolidatedPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*firewallConsolidatedPolicyArgs)(nil)).Elem()
}

type FirewallConsolidatedPolicyInput interface {
	pulumi.Input

	ToFirewallConsolidatedPolicyOutput() FirewallConsolidatedPolicyOutput
	ToFirewallConsolidatedPolicyOutputWithContext(ctx context.Context) FirewallConsolidatedPolicyOutput
}

func (*FirewallConsolidatedPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**FirewallConsolidatedPolicy)(nil)).Elem()
}

func (i *FirewallConsolidatedPolicy) ToFirewallConsolidatedPolicyOutput() FirewallConsolidatedPolicyOutput {
	return i.ToFirewallConsolidatedPolicyOutputWithContext(context.Background())
}

func (i *FirewallConsolidatedPolicy) ToFirewallConsolidatedPolicyOutputWithContext(ctx context.Context) FirewallConsolidatedPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallConsolidatedPolicyOutput)
}

// FirewallConsolidatedPolicyArrayInput is an input type that accepts FirewallConsolidatedPolicyArray and FirewallConsolidatedPolicyArrayOutput values.
// You can construct a concrete instance of `FirewallConsolidatedPolicyArrayInput` via:
//
//	FirewallConsolidatedPolicyArray{ FirewallConsolidatedPolicyArgs{...} }
type FirewallConsolidatedPolicyArrayInput interface {
	pulumi.Input

	ToFirewallConsolidatedPolicyArrayOutput() FirewallConsolidatedPolicyArrayOutput
	ToFirewallConsolidatedPolicyArrayOutputWithContext(context.Context) FirewallConsolidatedPolicyArrayOutput
}

type FirewallConsolidatedPolicyArray []FirewallConsolidatedPolicyInput

func (FirewallConsolidatedPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FirewallConsolidatedPolicy)(nil)).Elem()
}

func (i FirewallConsolidatedPolicyArray) ToFirewallConsolidatedPolicyArrayOutput() FirewallConsolidatedPolicyArrayOutput {
	return i.ToFirewallConsolidatedPolicyArrayOutputWithContext(context.Background())
}

func (i FirewallConsolidatedPolicyArray) ToFirewallConsolidatedPolicyArrayOutputWithContext(ctx context.Context) FirewallConsolidatedPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallConsolidatedPolicyArrayOutput)
}

// FirewallConsolidatedPolicyMapInput is an input type that accepts FirewallConsolidatedPolicyMap and FirewallConsolidatedPolicyMapOutput values.
// You can construct a concrete instance of `FirewallConsolidatedPolicyMapInput` via:
//
//	FirewallConsolidatedPolicyMap{ "key": FirewallConsolidatedPolicyArgs{...} }
type FirewallConsolidatedPolicyMapInput interface {
	pulumi.Input

	ToFirewallConsolidatedPolicyMapOutput() FirewallConsolidatedPolicyMapOutput
	ToFirewallConsolidatedPolicyMapOutputWithContext(context.Context) FirewallConsolidatedPolicyMapOutput
}

type FirewallConsolidatedPolicyMap map[string]FirewallConsolidatedPolicyInput

func (FirewallConsolidatedPolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FirewallConsolidatedPolicy)(nil)).Elem()
}

func (i FirewallConsolidatedPolicyMap) ToFirewallConsolidatedPolicyMapOutput() FirewallConsolidatedPolicyMapOutput {
	return i.ToFirewallConsolidatedPolicyMapOutputWithContext(context.Background())
}

func (i FirewallConsolidatedPolicyMap) ToFirewallConsolidatedPolicyMapOutputWithContext(ctx context.Context) FirewallConsolidatedPolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallConsolidatedPolicyMapOutput)
}

type FirewallConsolidatedPolicyOutput struct{ *pulumi.OutputState }

func (FirewallConsolidatedPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FirewallConsolidatedPolicy)(nil)).Elem()
}

func (o FirewallConsolidatedPolicyOutput) ToFirewallConsolidatedPolicyOutput() FirewallConsolidatedPolicyOutput {
	return o
}

func (o FirewallConsolidatedPolicyOutput) ToFirewallConsolidatedPolicyOutputWithContext(ctx context.Context) FirewallConsolidatedPolicyOutput {
	return o
}

func (o FirewallConsolidatedPolicyOutput) Action() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Action }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) AppCategories() FirewallConsolidatedPolicyAppCategoryArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyAppCategoryArrayOutput {
		return v.AppCategories
	}).(FirewallConsolidatedPolicyAppCategoryArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) AppGroups() FirewallConsolidatedPolicyAppGroupArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyAppGroupArrayOutput { return v.AppGroups }).(FirewallConsolidatedPolicyAppGroupArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) ApplicationList() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.ApplicationList }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Applications() FirewallConsolidatedPolicyApplicationArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyApplicationArrayOutput {
		return v.Applications
	}).(FirewallConsolidatedPolicyApplicationArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) AutoAsicOffload() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.AutoAsicOffload }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) AvProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.AvProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) CaptivePortalExempt() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.CaptivePortalExempt }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) CifsProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.CifsProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Comments() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringPtrOutput { return v.Comments }).(pulumi.StringPtrOutput)
}

func (o FirewallConsolidatedPolicyOutput) DiffservForward() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.DiffservForward }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) DiffservReverse() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.DiffservReverse }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) DiffservcodeForward() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.DiffservcodeForward }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) DiffservcodeRev() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.DiffservcodeRev }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) DlpSensor() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.DlpSensor }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) DnsfilterProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.DnsfilterProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Dstaddr4s() FirewallConsolidatedPolicyDstaddr4ArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyDstaddr4ArrayOutput { return v.Dstaddr4s }).(FirewallConsolidatedPolicyDstaddr4ArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) Dstaddr6s() FirewallConsolidatedPolicyDstaddr6ArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyDstaddr6ArrayOutput { return v.Dstaddr6s }).(FirewallConsolidatedPolicyDstaddr6ArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) DstaddrNegate() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.DstaddrNegate }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Dstintfs() FirewallConsolidatedPolicyDstintfArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyDstintfArrayOutput { return v.Dstintfs }).(FirewallConsolidatedPolicyDstintfArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) DynamicSortSubtable() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringPtrOutput { return v.DynamicSortSubtable }).(pulumi.StringPtrOutput)
}

func (o FirewallConsolidatedPolicyOutput) EmailfilterProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.EmailfilterProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Fixedport() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Fixedport }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) FssoGroups() FirewallConsolidatedPolicyFssoGroupArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyFssoGroupArrayOutput {
		return v.FssoGroups
	}).(FirewallConsolidatedPolicyFssoGroupArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) Groups() FirewallConsolidatedPolicyGroupArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyGroupArrayOutput { return v.Groups }).(FirewallConsolidatedPolicyGroupArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) HttpPolicyRedirect() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.HttpPolicyRedirect }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) IcapProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.IcapProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Inbound() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Inbound }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) InspectionMode() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.InspectionMode }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetService() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.InternetService }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceCustomGroups() FirewallConsolidatedPolicyInternetServiceCustomGroupArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyInternetServiceCustomGroupArrayOutput {
		return v.InternetServiceCustomGroups
	}).(FirewallConsolidatedPolicyInternetServiceCustomGroupArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceCustoms() FirewallConsolidatedPolicyInternetServiceCustomArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyInternetServiceCustomArrayOutput {
		return v.InternetServiceCustoms
	}).(FirewallConsolidatedPolicyInternetServiceCustomArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceGroups() FirewallConsolidatedPolicyInternetServiceGroupArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyInternetServiceGroupArrayOutput {
		return v.InternetServiceGroups
	}).(FirewallConsolidatedPolicyInternetServiceGroupArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceIds() FirewallConsolidatedPolicyInternetServiceIdArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyInternetServiceIdArrayOutput {
		return v.InternetServiceIds
	}).(FirewallConsolidatedPolicyInternetServiceIdArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceNames() FirewallConsolidatedPolicyInternetServiceNameArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyInternetServiceNameArrayOutput {
		return v.InternetServiceNames
	}).(FirewallConsolidatedPolicyInternetServiceNameArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceNegate() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.InternetServiceNegate }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceSrc() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.InternetServiceSrc }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceSrcCustomGroups() FirewallConsolidatedPolicyInternetServiceSrcCustomGroupArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyInternetServiceSrcCustomGroupArrayOutput {
		return v.InternetServiceSrcCustomGroups
	}).(FirewallConsolidatedPolicyInternetServiceSrcCustomGroupArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceSrcCustoms() FirewallConsolidatedPolicyInternetServiceSrcCustomArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyInternetServiceSrcCustomArrayOutput {
		return v.InternetServiceSrcCustoms
	}).(FirewallConsolidatedPolicyInternetServiceSrcCustomArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceSrcGroups() FirewallConsolidatedPolicyInternetServiceSrcGroupArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyInternetServiceSrcGroupArrayOutput {
		return v.InternetServiceSrcGroups
	}).(FirewallConsolidatedPolicyInternetServiceSrcGroupArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceSrcIds() FirewallConsolidatedPolicyInternetServiceSrcIdArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyInternetServiceSrcIdArrayOutput {
		return v.InternetServiceSrcIds
	}).(FirewallConsolidatedPolicyInternetServiceSrcIdArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceSrcNames() FirewallConsolidatedPolicyInternetServiceSrcNameArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyInternetServiceSrcNameArrayOutput {
		return v.InternetServiceSrcNames
	}).(FirewallConsolidatedPolicyInternetServiceSrcNameArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) InternetServiceSrcNegate() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.InternetServiceSrcNegate }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Ippool() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Ippool }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) IpsSensor() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.IpsSensor }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Logtraffic() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Logtraffic }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) LogtrafficStart() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.LogtrafficStart }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Nat() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Nat }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Outbound() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Outbound }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) PerIpShaper() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.PerIpShaper }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Policyid() pulumi.IntOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.IntOutput { return v.Policyid }).(pulumi.IntOutput)
}

func (o FirewallConsolidatedPolicyOutput) Poolname4s() FirewallConsolidatedPolicyPoolname4ArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyPoolname4ArrayOutput {
		return v.Poolname4s
	}).(FirewallConsolidatedPolicyPoolname4ArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) Poolname6s() FirewallConsolidatedPolicyPoolname6ArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyPoolname6ArrayOutput {
		return v.Poolname6s
	}).(FirewallConsolidatedPolicyPoolname6ArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) ProfileGroup() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.ProfileGroup }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) ProfileProtocolOptions() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.ProfileProtocolOptions }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) ProfileType() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.ProfileType }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Schedule() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Schedule }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) ServiceNegate() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.ServiceNegate }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Services() FirewallConsolidatedPolicyServiceArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyServiceArrayOutput { return v.Services }).(FirewallConsolidatedPolicyServiceArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) SessionTtl() pulumi.IntOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.IntOutput { return v.SessionTtl }).(pulumi.IntOutput)
}

func (o FirewallConsolidatedPolicyOutput) SpamfilterProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.SpamfilterProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Srcaddr4s() FirewallConsolidatedPolicySrcaddr4ArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicySrcaddr4ArrayOutput { return v.Srcaddr4s }).(FirewallConsolidatedPolicySrcaddr4ArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) Srcaddr6s() FirewallConsolidatedPolicySrcaddr6ArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicySrcaddr6ArrayOutput { return v.Srcaddr6s }).(FirewallConsolidatedPolicySrcaddr6ArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) SrcaddrNegate() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.SrcaddrNegate }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Srcintfs() FirewallConsolidatedPolicySrcintfArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicySrcintfArrayOutput { return v.Srcintfs }).(FirewallConsolidatedPolicySrcintfArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) SshFilterProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.SshFilterProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) SshPolicyRedirect() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.SshPolicyRedirect }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) SslSshProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.SslSshProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) TcpMssReceiver() pulumi.IntOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.IntOutput { return v.TcpMssReceiver }).(pulumi.IntOutput)
}

func (o FirewallConsolidatedPolicyOutput) TcpMssSender() pulumi.IntOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.IntOutput { return v.TcpMssSender }).(pulumi.IntOutput)
}

func (o FirewallConsolidatedPolicyOutput) TrafficShaper() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.TrafficShaper }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) TrafficShaperReverse() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.TrafficShaperReverse }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) UrlCategories() FirewallConsolidatedPolicyUrlCategoryArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyUrlCategoryArrayOutput {
		return v.UrlCategories
	}).(FirewallConsolidatedPolicyUrlCategoryArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) Users() FirewallConsolidatedPolicyUserArrayOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) FirewallConsolidatedPolicyUserArrayOutput { return v.Users }).(FirewallConsolidatedPolicyUserArrayOutput)
}

func (o FirewallConsolidatedPolicyOutput) UtmStatus() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.UtmStatus }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Uuid }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Vdomparam() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringPtrOutput { return v.Vdomparam }).(pulumi.StringPtrOutput)
}

func (o FirewallConsolidatedPolicyOutput) VoipProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.VoipProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Vpntunnel() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Vpntunnel }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) WafProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.WafProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Wanopt() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Wanopt }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) WanoptDetection() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.WanoptDetection }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) WanoptPassiveOpt() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.WanoptPassiveOpt }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) WanoptPeer() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.WanoptPeer }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) WanoptProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.WanoptProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) Webcache() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.Webcache }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) WebcacheHttps() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.WebcacheHttps }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) WebfilterProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.WebfilterProfile }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) WebproxyForwardServer() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.WebproxyForwardServer }).(pulumi.StringOutput)
}

func (o FirewallConsolidatedPolicyOutput) WebproxyProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallConsolidatedPolicy) pulumi.StringOutput { return v.WebproxyProfile }).(pulumi.StringOutput)
}

type FirewallConsolidatedPolicyArrayOutput struct{ *pulumi.OutputState }

func (FirewallConsolidatedPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FirewallConsolidatedPolicy)(nil)).Elem()
}

func (o FirewallConsolidatedPolicyArrayOutput) ToFirewallConsolidatedPolicyArrayOutput() FirewallConsolidatedPolicyArrayOutput {
	return o
}

func (o FirewallConsolidatedPolicyArrayOutput) ToFirewallConsolidatedPolicyArrayOutputWithContext(ctx context.Context) FirewallConsolidatedPolicyArrayOutput {
	return o
}

func (o FirewallConsolidatedPolicyArrayOutput) Index(i pulumi.IntInput) FirewallConsolidatedPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FirewallConsolidatedPolicy {
		return vs[0].([]*FirewallConsolidatedPolicy)[vs[1].(int)]
	}).(FirewallConsolidatedPolicyOutput)
}

type FirewallConsolidatedPolicyMapOutput struct{ *pulumi.OutputState }

func (FirewallConsolidatedPolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FirewallConsolidatedPolicy)(nil)).Elem()
}

func (o FirewallConsolidatedPolicyMapOutput) ToFirewallConsolidatedPolicyMapOutput() FirewallConsolidatedPolicyMapOutput {
	return o
}

func (o FirewallConsolidatedPolicyMapOutput) ToFirewallConsolidatedPolicyMapOutputWithContext(ctx context.Context) FirewallConsolidatedPolicyMapOutput {
	return o
}

func (o FirewallConsolidatedPolicyMapOutput) MapIndex(k pulumi.StringInput) FirewallConsolidatedPolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FirewallConsolidatedPolicy {
		return vs[0].(map[string]*FirewallConsolidatedPolicy)[vs[1].(string)]
	}).(FirewallConsolidatedPolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallConsolidatedPolicyInput)(nil)).Elem(), &FirewallConsolidatedPolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallConsolidatedPolicyArrayInput)(nil)).Elem(), FirewallConsolidatedPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallConsolidatedPolicyMapInput)(nil)).Elem(), FirewallConsolidatedPolicyMap{})
	pulumi.RegisterOutputType(FirewallConsolidatedPolicyOutput{})
	pulumi.RegisterOutputType(FirewallConsolidatedPolicyArrayOutput{})
	pulumi.RegisterOutputType(FirewallConsolidatedPolicyMapOutput{})
}
