// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get information on an fortios firewallshaper trafficshaper
func LookupFirewallShaperTrafficShaper(ctx *pulumi.Context, args *LookupFirewallShaperTrafficShaperArgs, opts ...pulumi.InvokeOption) (*LookupFirewallShaperTrafficShaperResult, error) {
	var rv LookupFirewallShaperTrafficShaperResult
	err := ctx.Invoke("fortios:index/getFirewallShaperTrafficShaper:GetFirewallShaperTrafficShaper", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetFirewallShaperTrafficShaper.
type LookupFirewallShaperTrafficShaperArgs struct {
	// Specify the name of the desired firewallshaper trafficshaper.
	Name string `pulumi:"name"`
	// Specifies the vdom to which the data source will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

// A collection of values returned by GetFirewallShaperTrafficShaper.
type LookupFirewallShaperTrafficShaperResult struct {
	// Unit of measurement for guaranteed and maximum bandwidth for this shaper (Kbps, Mbps or Gbps).
	BandwidthUnit string `pulumi:"bandwidthUnit"`
	// Enable/disable changing the DiffServ setting applied to traffic accepted by this shaper.
	Diffserv string `pulumi:"diffserv"`
	// DiffServ setting to be applied to traffic accepted by this shaper.
	Diffservcode string `pulumi:"diffservcode"`
	// Select DSCP marking method.
	DscpMarkingMethod string `pulumi:"dscpMarkingMethod"`
	// Exceed bandwidth used for DSCP multi-stage marking. Units depend on the bandwidth-unit setting.
	ExceedBandwidth int `pulumi:"exceedBandwidth"`
	// Class ID for traffic in [guaranteed-bandwidth, maximum-bandwidth].
	ExceedClassId int `pulumi:"exceedClassId"`
	// DSCP mark for traffic in [guaranteed-bandwidth, exceed-bandwidth].
	ExceedDscp string `pulumi:"exceedDscp"`
	// Amount of bandwidth guaranteed for this shaper (0 - 16776000). Units depend on the bandwidth-unit setting.
	GuaranteedBandwidth int `pulumi:"guaranteedBandwidth"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Upper bandwidth limit enforced by this shaper (0 - 16776000). 0 means no limit. Units depend on the bandwidth-unit setting.
	MaximumBandwidth int `pulumi:"maximumBandwidth"`
	// DSCP mark for traffic in [exceed-bandwidth, maximum-bandwidth].
	MaximumDscp string `pulumi:"maximumDscp"`
	// Traffic shaper name.
	Name string `pulumi:"name"`
	// Per-packet size overhead used in rate computations.
	Overhead int `pulumi:"overhead"`
	// Enable/disable applying a separate shaper for each policy. For example, if enabled the guaranteed bandwidth is applied separately for each policy.
	PerPolicy string `pulumi:"perPolicy"`
	// Higher priority traffic is more likely to be forwarded without delays and without compromising the guaranteed bandwidth.
	Priority  string  `pulumi:"priority"`
	Vdomparam *string `pulumi:"vdomparam"`
}
