// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupRouterStatic6(ctx *pulumi.Context, args *LookupRouterStatic6Args, opts ...pulumi.InvokeOption) (*LookupRouterStatic6Result, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupRouterStatic6Result
	err := ctx.Invoke("fortios:index/getRouterStatic6:GetRouterStatic6", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetRouterStatic6.
type LookupRouterStatic6Args struct {
	SeqNum    int     `pulumi:"seqNum"`
	Vdomparam *string `pulumi:"vdomparam"`
}

// A collection of values returned by GetRouterStatic6.
type LookupRouterStatic6Result struct {
	Bfd            string `pulumi:"bfd"`
	Blackhole      string `pulumi:"blackhole"`
	Comment        string `pulumi:"comment"`
	Device         string `pulumi:"device"`
	Devindex       int    `pulumi:"devindex"`
	Distance       int    `pulumi:"distance"`
	Dst            string `pulumi:"dst"`
	Dstaddr        string `pulumi:"dstaddr"`
	DynamicGateway string `pulumi:"dynamicGateway"`
	Gateway        string `pulumi:"gateway"`
	// The provider-assigned unique ID for this managed resource.
	Id                string                      `pulumi:"id"`
	LinkMonitorExempt string                      `pulumi:"linkMonitorExempt"`
	Priority          int                         `pulumi:"priority"`
	Sdwan             string                      `pulumi:"sdwan"`
	SdwanZones        []GetRouterStatic6SdwanZone `pulumi:"sdwanZones"`
	SeqNum            int                         `pulumi:"seqNum"`
	Status            string                      `pulumi:"status"`
	Vdomparam         *string                     `pulumi:"vdomparam"`
	VirtualWanLink    string                      `pulumi:"virtualWanLink"`
	Vrf               int                         `pulumi:"vrf"`
	Weight            int                         `pulumi:"weight"`
}

func LookupRouterStatic6Output(ctx *pulumi.Context, args LookupRouterStatic6OutputArgs, opts ...pulumi.InvokeOption) LookupRouterStatic6ResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupRouterStatic6Result, error) {
			args := v.(LookupRouterStatic6Args)
			r, err := LookupRouterStatic6(ctx, &args, opts...)
			var s LookupRouterStatic6Result
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupRouterStatic6ResultOutput)
}

// A collection of arguments for invoking GetRouterStatic6.
type LookupRouterStatic6OutputArgs struct {
	SeqNum    pulumi.IntInput       `pulumi:"seqNum"`
	Vdomparam pulumi.StringPtrInput `pulumi:"vdomparam"`
}

func (LookupRouterStatic6OutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRouterStatic6Args)(nil)).Elem()
}

// A collection of values returned by GetRouterStatic6.
type LookupRouterStatic6ResultOutput struct{ *pulumi.OutputState }

func (LookupRouterStatic6ResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRouterStatic6Result)(nil)).Elem()
}

func (o LookupRouterStatic6ResultOutput) ToLookupRouterStatic6ResultOutput() LookupRouterStatic6ResultOutput {
	return o
}

func (o LookupRouterStatic6ResultOutput) ToLookupRouterStatic6ResultOutputWithContext(ctx context.Context) LookupRouterStatic6ResultOutput {
	return o
}

func (o LookupRouterStatic6ResultOutput) Bfd() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.Bfd }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) Blackhole() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.Blackhole }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.Comment }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) Device() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.Device }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) Devindex() pulumi.IntOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) int { return v.Devindex }).(pulumi.IntOutput)
}

func (o LookupRouterStatic6ResultOutput) Distance() pulumi.IntOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) int { return v.Distance }).(pulumi.IntOutput)
}

func (o LookupRouterStatic6ResultOutput) Dst() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.Dst }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) Dstaddr() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.Dstaddr }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) DynamicGateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.DynamicGateway }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.Gateway }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupRouterStatic6ResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) LinkMonitorExempt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.LinkMonitorExempt }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) Priority() pulumi.IntOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) int { return v.Priority }).(pulumi.IntOutput)
}

func (o LookupRouterStatic6ResultOutput) Sdwan() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.Sdwan }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) SdwanZones() GetRouterStatic6SdwanZoneArrayOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) []GetRouterStatic6SdwanZone { return v.SdwanZones }).(GetRouterStatic6SdwanZoneArrayOutput)
}

func (o LookupRouterStatic6ResultOutput) SeqNum() pulumi.IntOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) int { return v.SeqNum }).(pulumi.IntOutput)
}

func (o LookupRouterStatic6ResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) Vdomparam() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) *string { return v.Vdomparam }).(pulumi.StringPtrOutput)
}

func (o LookupRouterStatic6ResultOutput) VirtualWanLink() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) string { return v.VirtualWanLink }).(pulumi.StringOutput)
}

func (o LookupRouterStatic6ResultOutput) Vrf() pulumi.IntOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) int { return v.Vrf }).(pulumi.IntOutput)
}

func (o LookupRouterStatic6ResultOutput) Weight() pulumi.IntOutput {
	return o.ApplyT(func(v LookupRouterStatic6Result) int { return v.Weight }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupRouterStatic6ResultOutput{})
}
