// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Global settings for remote syslog server.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/lubyou/pulumi-fortios/sdk/go/fortios"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := fortios.NewLogSyslogd3Setting(ctx, "trname", &fortios.LogSyslogd3SettingArgs{
// 			EncAlgorithm:       pulumi.String("disable"),
// 			Facility:           pulumi.String("local7"),
// 			Format:             pulumi.String("default"),
// 			Mode:               pulumi.String("udp"),
// 			Port:               pulumi.Int(514),
// 			SslMinProtoVersion: pulumi.String("default"),
// 			Status:             pulumi.String("disable"),
// 			SyslogType:         pulumi.Int(3),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// LogSyslogd3 Setting can be imported using any of these accepted formats$ export "FORTIOS_IMPORT_TABLE"="true"
//
// ```sh
//  $ pulumi import fortios:index/logSyslogd3Setting:LogSyslogd3Setting labelname LogSyslogd3Setting
// ```
//
//  $ unset "FORTIOS_IMPORT_TABLE"
type LogSyslogd3Setting struct {
	pulumi.CustomResourceState

	// Certificate used to communicate with Syslog server.
	Certificate pulumi.StringOutput `pulumi:"certificate"`
	// Custom field name for CEF format logging. The structure of `customFieldName` block is documented below.
	CustomFieldNames LogSyslogd3SettingCustomFieldNameArrayOutput `pulumi:"customFieldNames"`
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable pulumi.StringPtrOutput `pulumi:"dynamicSortSubtable"`
	// Enable/disable reliable syslogging with TLS encryption. Valid values: `high-medium`, `high`, `low`, `disable`.
	EncAlgorithm pulumi.StringOutput `pulumi:"encAlgorithm"`
	// Remote syslog facility. Valid values: `kernel`, `user`, `mail`, `daemon`, `auth`, `syslog`, `lpr`, `news`, `uucp`, `cron`, `authpriv`, `ftp`, `ntp`, `audit`, `alert`, `clock`, `local0`, `local1`, `local2`, `local3`, `local4`, `local5`, `local6`, `local7`.
	Facility pulumi.StringOutput `pulumi:"facility"`
	// Log format.
	Format pulumi.StringOutput `pulumi:"format"`
	// Specify outgoing interface to reach server.
	Interface pulumi.StringOutput `pulumi:"interface"`
	// Specify how to select outgoing interface to reach server. Valid values: `auto`, `sdwan`, `specify`.
	InterfaceSelectMethod pulumi.StringOutput `pulumi:"interfaceSelectMethod"`
	// Syslog maximum log rate in MBps (0 = unlimited).
	MaxLogRate pulumi.IntOutput `pulumi:"maxLogRate"`
	// Remote syslog logging over UDP/Reliable TCP. Valid values: `udp`, `legacy-reliable`, `reliable`.
	Mode pulumi.StringOutput `pulumi:"mode"`
	// Server listen port.
	Port pulumi.IntOutput `pulumi:"port"`
	// Set log transmission priority. Valid values: `default`, `low`.
	Priority pulumi.StringOutput `pulumi:"priority"`
	// Address of remote syslog server.
	Server pulumi.StringOutput `pulumi:"server"`
	// Source IP address of syslog.
	SourceIp pulumi.StringOutput `pulumi:"sourceIp"`
	// Minimum supported protocol version for SSL/TLS connections (default is to follow system global setting). Valid values: `default`, `SSLv3`, `TLSv1`, `TLSv1-1`, `TLSv1-2`.
	SslMinProtoVersion pulumi.StringOutput `pulumi:"sslMinProtoVersion"`
	// Enable/disable remote syslog logging. Valid values: `enable`, `disable`.
	Status pulumi.StringOutput `pulumi:"status"`
	// Hidden setting index of Syslog.
	SyslogType pulumi.IntOutput `pulumi:"syslogType"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrOutput `pulumi:"vdomparam"`
}

// NewLogSyslogd3Setting registers a new resource with the given unique name, arguments, and options.
func NewLogSyslogd3Setting(ctx *pulumi.Context,
	name string, args *LogSyslogd3SettingArgs, opts ...pulumi.ResourceOption) (*LogSyslogd3Setting, error) {
	if args == nil {
		args = &LogSyslogd3SettingArgs{}
	}

	opts = pkgResourceDefaultOpts(opts)
	var resource LogSyslogd3Setting
	err := ctx.RegisterResource("fortios:index/logSyslogd3Setting:LogSyslogd3Setting", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLogSyslogd3Setting gets an existing LogSyslogd3Setting resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLogSyslogd3Setting(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LogSyslogd3SettingState, opts ...pulumi.ResourceOption) (*LogSyslogd3Setting, error) {
	var resource LogSyslogd3Setting
	err := ctx.ReadResource("fortios:index/logSyslogd3Setting:LogSyslogd3Setting", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LogSyslogd3Setting resources.
type logSyslogd3SettingState struct {
	// Certificate used to communicate with Syslog server.
	Certificate *string `pulumi:"certificate"`
	// Custom field name for CEF format logging. The structure of `customFieldName` block is documented below.
	CustomFieldNames []LogSyslogd3SettingCustomFieldName `pulumi:"customFieldNames"`
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable *string `pulumi:"dynamicSortSubtable"`
	// Enable/disable reliable syslogging with TLS encryption. Valid values: `high-medium`, `high`, `low`, `disable`.
	EncAlgorithm *string `pulumi:"encAlgorithm"`
	// Remote syslog facility. Valid values: `kernel`, `user`, `mail`, `daemon`, `auth`, `syslog`, `lpr`, `news`, `uucp`, `cron`, `authpriv`, `ftp`, `ntp`, `audit`, `alert`, `clock`, `local0`, `local1`, `local2`, `local3`, `local4`, `local5`, `local6`, `local7`.
	Facility *string `pulumi:"facility"`
	// Log format.
	Format *string `pulumi:"format"`
	// Specify outgoing interface to reach server.
	Interface *string `pulumi:"interface"`
	// Specify how to select outgoing interface to reach server. Valid values: `auto`, `sdwan`, `specify`.
	InterfaceSelectMethod *string `pulumi:"interfaceSelectMethod"`
	// Syslog maximum log rate in MBps (0 = unlimited).
	MaxLogRate *int `pulumi:"maxLogRate"`
	// Remote syslog logging over UDP/Reliable TCP. Valid values: `udp`, `legacy-reliable`, `reliable`.
	Mode *string `pulumi:"mode"`
	// Server listen port.
	Port *int `pulumi:"port"`
	// Set log transmission priority. Valid values: `default`, `low`.
	Priority *string `pulumi:"priority"`
	// Address of remote syslog server.
	Server *string `pulumi:"server"`
	// Source IP address of syslog.
	SourceIp *string `pulumi:"sourceIp"`
	// Minimum supported protocol version for SSL/TLS connections (default is to follow system global setting). Valid values: `default`, `SSLv3`, `TLSv1`, `TLSv1-1`, `TLSv1-2`.
	SslMinProtoVersion *string `pulumi:"sslMinProtoVersion"`
	// Enable/disable remote syslog logging. Valid values: `enable`, `disable`.
	Status *string `pulumi:"status"`
	// Hidden setting index of Syslog.
	SyslogType *int `pulumi:"syslogType"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

type LogSyslogd3SettingState struct {
	// Certificate used to communicate with Syslog server.
	Certificate pulumi.StringPtrInput
	// Custom field name for CEF format logging. The structure of `customFieldName` block is documented below.
	CustomFieldNames LogSyslogd3SettingCustomFieldNameArrayInput
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable pulumi.StringPtrInput
	// Enable/disable reliable syslogging with TLS encryption. Valid values: `high-medium`, `high`, `low`, `disable`.
	EncAlgorithm pulumi.StringPtrInput
	// Remote syslog facility. Valid values: `kernel`, `user`, `mail`, `daemon`, `auth`, `syslog`, `lpr`, `news`, `uucp`, `cron`, `authpriv`, `ftp`, `ntp`, `audit`, `alert`, `clock`, `local0`, `local1`, `local2`, `local3`, `local4`, `local5`, `local6`, `local7`.
	Facility pulumi.StringPtrInput
	// Log format.
	Format pulumi.StringPtrInput
	// Specify outgoing interface to reach server.
	Interface pulumi.StringPtrInput
	// Specify how to select outgoing interface to reach server. Valid values: `auto`, `sdwan`, `specify`.
	InterfaceSelectMethod pulumi.StringPtrInput
	// Syslog maximum log rate in MBps (0 = unlimited).
	MaxLogRate pulumi.IntPtrInput
	// Remote syslog logging over UDP/Reliable TCP. Valid values: `udp`, `legacy-reliable`, `reliable`.
	Mode pulumi.StringPtrInput
	// Server listen port.
	Port pulumi.IntPtrInput
	// Set log transmission priority. Valid values: `default`, `low`.
	Priority pulumi.StringPtrInput
	// Address of remote syslog server.
	Server pulumi.StringPtrInput
	// Source IP address of syslog.
	SourceIp pulumi.StringPtrInput
	// Minimum supported protocol version for SSL/TLS connections (default is to follow system global setting). Valid values: `default`, `SSLv3`, `TLSv1`, `TLSv1-1`, `TLSv1-2`.
	SslMinProtoVersion pulumi.StringPtrInput
	// Enable/disable remote syslog logging. Valid values: `enable`, `disable`.
	Status pulumi.StringPtrInput
	// Hidden setting index of Syslog.
	SyslogType pulumi.IntPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (LogSyslogd3SettingState) ElementType() reflect.Type {
	return reflect.TypeOf((*logSyslogd3SettingState)(nil)).Elem()
}

type logSyslogd3SettingArgs struct {
	// Certificate used to communicate with Syslog server.
	Certificate *string `pulumi:"certificate"`
	// Custom field name for CEF format logging. The structure of `customFieldName` block is documented below.
	CustomFieldNames []LogSyslogd3SettingCustomFieldName `pulumi:"customFieldNames"`
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable *string `pulumi:"dynamicSortSubtable"`
	// Enable/disable reliable syslogging with TLS encryption. Valid values: `high-medium`, `high`, `low`, `disable`.
	EncAlgorithm *string `pulumi:"encAlgorithm"`
	// Remote syslog facility. Valid values: `kernel`, `user`, `mail`, `daemon`, `auth`, `syslog`, `lpr`, `news`, `uucp`, `cron`, `authpriv`, `ftp`, `ntp`, `audit`, `alert`, `clock`, `local0`, `local1`, `local2`, `local3`, `local4`, `local5`, `local6`, `local7`.
	Facility *string `pulumi:"facility"`
	// Log format.
	Format *string `pulumi:"format"`
	// Specify outgoing interface to reach server.
	Interface *string `pulumi:"interface"`
	// Specify how to select outgoing interface to reach server. Valid values: `auto`, `sdwan`, `specify`.
	InterfaceSelectMethod *string `pulumi:"interfaceSelectMethod"`
	// Syslog maximum log rate in MBps (0 = unlimited).
	MaxLogRate *int `pulumi:"maxLogRate"`
	// Remote syslog logging over UDP/Reliable TCP. Valid values: `udp`, `legacy-reliable`, `reliable`.
	Mode *string `pulumi:"mode"`
	// Server listen port.
	Port *int `pulumi:"port"`
	// Set log transmission priority. Valid values: `default`, `low`.
	Priority *string `pulumi:"priority"`
	// Address of remote syslog server.
	Server *string `pulumi:"server"`
	// Source IP address of syslog.
	SourceIp *string `pulumi:"sourceIp"`
	// Minimum supported protocol version for SSL/TLS connections (default is to follow system global setting). Valid values: `default`, `SSLv3`, `TLSv1`, `TLSv1-1`, `TLSv1-2`.
	SslMinProtoVersion *string `pulumi:"sslMinProtoVersion"`
	// Enable/disable remote syslog logging. Valid values: `enable`, `disable`.
	Status *string `pulumi:"status"`
	// Hidden setting index of Syslog.
	SyslogType *int `pulumi:"syslogType"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

// The set of arguments for constructing a LogSyslogd3Setting resource.
type LogSyslogd3SettingArgs struct {
	// Certificate used to communicate with Syslog server.
	Certificate pulumi.StringPtrInput
	// Custom field name for CEF format logging. The structure of `customFieldName` block is documented below.
	CustomFieldNames LogSyslogd3SettingCustomFieldNameArrayInput
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable pulumi.StringPtrInput
	// Enable/disable reliable syslogging with TLS encryption. Valid values: `high-medium`, `high`, `low`, `disable`.
	EncAlgorithm pulumi.StringPtrInput
	// Remote syslog facility. Valid values: `kernel`, `user`, `mail`, `daemon`, `auth`, `syslog`, `lpr`, `news`, `uucp`, `cron`, `authpriv`, `ftp`, `ntp`, `audit`, `alert`, `clock`, `local0`, `local1`, `local2`, `local3`, `local4`, `local5`, `local6`, `local7`.
	Facility pulumi.StringPtrInput
	// Log format.
	Format pulumi.StringPtrInput
	// Specify outgoing interface to reach server.
	Interface pulumi.StringPtrInput
	// Specify how to select outgoing interface to reach server. Valid values: `auto`, `sdwan`, `specify`.
	InterfaceSelectMethod pulumi.StringPtrInput
	// Syslog maximum log rate in MBps (0 = unlimited).
	MaxLogRate pulumi.IntPtrInput
	// Remote syslog logging over UDP/Reliable TCP. Valid values: `udp`, `legacy-reliable`, `reliable`.
	Mode pulumi.StringPtrInput
	// Server listen port.
	Port pulumi.IntPtrInput
	// Set log transmission priority. Valid values: `default`, `low`.
	Priority pulumi.StringPtrInput
	// Address of remote syslog server.
	Server pulumi.StringPtrInput
	// Source IP address of syslog.
	SourceIp pulumi.StringPtrInput
	// Minimum supported protocol version for SSL/TLS connections (default is to follow system global setting). Valid values: `default`, `SSLv3`, `TLSv1`, `TLSv1-1`, `TLSv1-2`.
	SslMinProtoVersion pulumi.StringPtrInput
	// Enable/disable remote syslog logging. Valid values: `enable`, `disable`.
	Status pulumi.StringPtrInput
	// Hidden setting index of Syslog.
	SyslogType pulumi.IntPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (LogSyslogd3SettingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*logSyslogd3SettingArgs)(nil)).Elem()
}

type LogSyslogd3SettingInput interface {
	pulumi.Input

	ToLogSyslogd3SettingOutput() LogSyslogd3SettingOutput
	ToLogSyslogd3SettingOutputWithContext(ctx context.Context) LogSyslogd3SettingOutput
}

func (*LogSyslogd3Setting) ElementType() reflect.Type {
	return reflect.TypeOf((**LogSyslogd3Setting)(nil)).Elem()
}

func (i *LogSyslogd3Setting) ToLogSyslogd3SettingOutput() LogSyslogd3SettingOutput {
	return i.ToLogSyslogd3SettingOutputWithContext(context.Background())
}

func (i *LogSyslogd3Setting) ToLogSyslogd3SettingOutputWithContext(ctx context.Context) LogSyslogd3SettingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogSyslogd3SettingOutput)
}

// LogSyslogd3SettingArrayInput is an input type that accepts LogSyslogd3SettingArray and LogSyslogd3SettingArrayOutput values.
// You can construct a concrete instance of `LogSyslogd3SettingArrayInput` via:
//
//          LogSyslogd3SettingArray{ LogSyslogd3SettingArgs{...} }
type LogSyslogd3SettingArrayInput interface {
	pulumi.Input

	ToLogSyslogd3SettingArrayOutput() LogSyslogd3SettingArrayOutput
	ToLogSyslogd3SettingArrayOutputWithContext(context.Context) LogSyslogd3SettingArrayOutput
}

type LogSyslogd3SettingArray []LogSyslogd3SettingInput

func (LogSyslogd3SettingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LogSyslogd3Setting)(nil)).Elem()
}

func (i LogSyslogd3SettingArray) ToLogSyslogd3SettingArrayOutput() LogSyslogd3SettingArrayOutput {
	return i.ToLogSyslogd3SettingArrayOutputWithContext(context.Background())
}

func (i LogSyslogd3SettingArray) ToLogSyslogd3SettingArrayOutputWithContext(ctx context.Context) LogSyslogd3SettingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogSyslogd3SettingArrayOutput)
}

// LogSyslogd3SettingMapInput is an input type that accepts LogSyslogd3SettingMap and LogSyslogd3SettingMapOutput values.
// You can construct a concrete instance of `LogSyslogd3SettingMapInput` via:
//
//          LogSyslogd3SettingMap{ "key": LogSyslogd3SettingArgs{...} }
type LogSyslogd3SettingMapInput interface {
	pulumi.Input

	ToLogSyslogd3SettingMapOutput() LogSyslogd3SettingMapOutput
	ToLogSyslogd3SettingMapOutputWithContext(context.Context) LogSyslogd3SettingMapOutput
}

type LogSyslogd3SettingMap map[string]LogSyslogd3SettingInput

func (LogSyslogd3SettingMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LogSyslogd3Setting)(nil)).Elem()
}

func (i LogSyslogd3SettingMap) ToLogSyslogd3SettingMapOutput() LogSyslogd3SettingMapOutput {
	return i.ToLogSyslogd3SettingMapOutputWithContext(context.Background())
}

func (i LogSyslogd3SettingMap) ToLogSyslogd3SettingMapOutputWithContext(ctx context.Context) LogSyslogd3SettingMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogSyslogd3SettingMapOutput)
}

type LogSyslogd3SettingOutput struct{ *pulumi.OutputState }

func (LogSyslogd3SettingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LogSyslogd3Setting)(nil)).Elem()
}

func (o LogSyslogd3SettingOutput) ToLogSyslogd3SettingOutput() LogSyslogd3SettingOutput {
	return o
}

func (o LogSyslogd3SettingOutput) ToLogSyslogd3SettingOutputWithContext(ctx context.Context) LogSyslogd3SettingOutput {
	return o
}

type LogSyslogd3SettingArrayOutput struct{ *pulumi.OutputState }

func (LogSyslogd3SettingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LogSyslogd3Setting)(nil)).Elem()
}

func (o LogSyslogd3SettingArrayOutput) ToLogSyslogd3SettingArrayOutput() LogSyslogd3SettingArrayOutput {
	return o
}

func (o LogSyslogd3SettingArrayOutput) ToLogSyslogd3SettingArrayOutputWithContext(ctx context.Context) LogSyslogd3SettingArrayOutput {
	return o
}

func (o LogSyslogd3SettingArrayOutput) Index(i pulumi.IntInput) LogSyslogd3SettingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *LogSyslogd3Setting {
		return vs[0].([]*LogSyslogd3Setting)[vs[1].(int)]
	}).(LogSyslogd3SettingOutput)
}

type LogSyslogd3SettingMapOutput struct{ *pulumi.OutputState }

func (LogSyslogd3SettingMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LogSyslogd3Setting)(nil)).Elem()
}

func (o LogSyslogd3SettingMapOutput) ToLogSyslogd3SettingMapOutput() LogSyslogd3SettingMapOutput {
	return o
}

func (o LogSyslogd3SettingMapOutput) ToLogSyslogd3SettingMapOutputWithContext(ctx context.Context) LogSyslogd3SettingMapOutput {
	return o
}

func (o LogSyslogd3SettingMapOutput) MapIndex(k pulumi.StringInput) LogSyslogd3SettingOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *LogSyslogd3Setting {
		return vs[0].(map[string]*LogSyslogd3Setting)[vs[1].(string)]
	}).(LogSyslogd3SettingOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LogSyslogd3SettingInput)(nil)).Elem(), &LogSyslogd3Setting{})
	pulumi.RegisterInputType(reflect.TypeOf((*LogSyslogd3SettingArrayInput)(nil)).Elem(), LogSyslogd3SettingArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*LogSyslogd3SettingMapInput)(nil)).Elem(), LogSyslogd3SettingMap{})
	pulumi.RegisterOutputType(LogSyslogd3SettingOutput{})
	pulumi.RegisterOutputType(LogSyslogd3SettingArrayOutput{})
	pulumi.RegisterOutputType(LogSyslogd3SettingMapOutput{})
}
