// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Override settings for remote syslog server.
//
// ## Import
//
// LogSyslogd OverrideSetting can be imported using any of these accepted formats
//
// ```sh
//  $ pulumi import fortios:index/logSyslogdOverrideSetting:LogSyslogdOverrideSetting labelname LogSyslogdOverrideSetting
// ```
//
//  If you do not want to import arguments of block$ export "FORTIOS_IMPORT_TABLE"="false"
//
// ```sh
//  $ pulumi import fortios:index/logSyslogdOverrideSetting:LogSyslogdOverrideSetting labelname LogSyslogdOverrideSetting
// ```
//
//  $ unset "FORTIOS_IMPORT_TABLE"
type LogSyslogdOverrideSetting struct {
	pulumi.CustomResourceState

	// Certificate used to communicate with Syslog server.
	Certificate pulumi.StringOutput `pulumi:"certificate"`
	// Custom field name for CEF format logging. The structure of `customFieldName` block is documented below.
	CustomFieldNames LogSyslogdOverrideSettingCustomFieldNameArrayOutput `pulumi:"customFieldNames"`
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable pulumi.StringPtrOutput `pulumi:"dynamicSortSubtable"`
	// Enable/disable reliable syslogging with TLS encryption. Valid values: `high-medium`, `high`, `low`, `disable`.
	EncAlgorithm pulumi.StringOutput `pulumi:"encAlgorithm"`
	// Remote syslog facility. Valid values: `kernel`, `user`, `mail`, `daemon`, `auth`, `syslog`, `lpr`, `news`, `uucp`, `cron`, `authpriv`, `ftp`, `ntp`, `audit`, `alert`, `clock`, `local0`, `local1`, `local2`, `local3`, `local4`, `local5`, `local6`, `local7`.
	Facility pulumi.StringOutput `pulumi:"facility"`
	// Log format.
	Format pulumi.StringOutput `pulumi:"format"`
	// Specify outgoing interface to reach server.
	Interface pulumi.StringOutput `pulumi:"interface"`
	// Specify how to select outgoing interface to reach server. Valid values: `auto`, `sdwan`, `specify`.
	InterfaceSelectMethod pulumi.StringOutput `pulumi:"interfaceSelectMethod"`
	// Syslog maximum log rate in MBps (0 = unlimited).
	MaxLogRate pulumi.IntOutput `pulumi:"maxLogRate"`
	// Remote syslog logging over UDP/Reliable TCP. Valid values: `udp`, `legacy-reliable`, `reliable`.
	Mode pulumi.StringOutput `pulumi:"mode"`
	// Enable/disable override syslog settings. Valid values: `enable`, `disable`.
	Override pulumi.StringOutput `pulumi:"override"`
	// Server listen port.
	Port pulumi.IntOutput `pulumi:"port"`
	// Set log transmission priority. Valid values: `default`, `low`.
	Priority pulumi.StringOutput `pulumi:"priority"`
	// Address of remote syslog server.
	Server pulumi.StringOutput `pulumi:"server"`
	// Source IP address of syslog.
	SourceIp pulumi.StringOutput `pulumi:"sourceIp"`
	// Minimum supported protocol version for SSL/TLS connections (default is to follow system global setting). Valid values: `default`, `SSLv3`, `TLSv1`, `TLSv1-1`, `TLSv1-2`.
	SslMinProtoVersion pulumi.StringOutput `pulumi:"sslMinProtoVersion"`
	// Enable/disable remote syslog logging. Valid values: `enable`, `disable`.
	Status pulumi.StringOutput `pulumi:"status"`
	// Hidden setting index of Syslog.
	SyslogType pulumi.IntOutput `pulumi:"syslogType"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrOutput `pulumi:"vdomparam"`
}

// NewLogSyslogdOverrideSetting registers a new resource with the given unique name, arguments, and options.
func NewLogSyslogdOverrideSetting(ctx *pulumi.Context,
	name string, args *LogSyslogdOverrideSettingArgs, opts ...pulumi.ResourceOption) (*LogSyslogdOverrideSetting, error) {
	if args == nil {
		args = &LogSyslogdOverrideSettingArgs{}
	}

	opts = pkgResourceDefaultOpts(opts)
	var resource LogSyslogdOverrideSetting
	err := ctx.RegisterResource("fortios:index/logSyslogdOverrideSetting:LogSyslogdOverrideSetting", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLogSyslogdOverrideSetting gets an existing LogSyslogdOverrideSetting resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLogSyslogdOverrideSetting(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LogSyslogdOverrideSettingState, opts ...pulumi.ResourceOption) (*LogSyslogdOverrideSetting, error) {
	var resource LogSyslogdOverrideSetting
	err := ctx.ReadResource("fortios:index/logSyslogdOverrideSetting:LogSyslogdOverrideSetting", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LogSyslogdOverrideSetting resources.
type logSyslogdOverrideSettingState struct {
	// Certificate used to communicate with Syslog server.
	Certificate *string `pulumi:"certificate"`
	// Custom field name for CEF format logging. The structure of `customFieldName` block is documented below.
	CustomFieldNames []LogSyslogdOverrideSettingCustomFieldName `pulumi:"customFieldNames"`
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable *string `pulumi:"dynamicSortSubtable"`
	// Enable/disable reliable syslogging with TLS encryption. Valid values: `high-medium`, `high`, `low`, `disable`.
	EncAlgorithm *string `pulumi:"encAlgorithm"`
	// Remote syslog facility. Valid values: `kernel`, `user`, `mail`, `daemon`, `auth`, `syslog`, `lpr`, `news`, `uucp`, `cron`, `authpriv`, `ftp`, `ntp`, `audit`, `alert`, `clock`, `local0`, `local1`, `local2`, `local3`, `local4`, `local5`, `local6`, `local7`.
	Facility *string `pulumi:"facility"`
	// Log format.
	Format *string `pulumi:"format"`
	// Specify outgoing interface to reach server.
	Interface *string `pulumi:"interface"`
	// Specify how to select outgoing interface to reach server. Valid values: `auto`, `sdwan`, `specify`.
	InterfaceSelectMethod *string `pulumi:"interfaceSelectMethod"`
	// Syslog maximum log rate in MBps (0 = unlimited).
	MaxLogRate *int `pulumi:"maxLogRate"`
	// Remote syslog logging over UDP/Reliable TCP. Valid values: `udp`, `legacy-reliable`, `reliable`.
	Mode *string `pulumi:"mode"`
	// Enable/disable override syslog settings. Valid values: `enable`, `disable`.
	Override *string `pulumi:"override"`
	// Server listen port.
	Port *int `pulumi:"port"`
	// Set log transmission priority. Valid values: `default`, `low`.
	Priority *string `pulumi:"priority"`
	// Address of remote syslog server.
	Server *string `pulumi:"server"`
	// Source IP address of syslog.
	SourceIp *string `pulumi:"sourceIp"`
	// Minimum supported protocol version for SSL/TLS connections (default is to follow system global setting). Valid values: `default`, `SSLv3`, `TLSv1`, `TLSv1-1`, `TLSv1-2`.
	SslMinProtoVersion *string `pulumi:"sslMinProtoVersion"`
	// Enable/disable remote syslog logging. Valid values: `enable`, `disable`.
	Status *string `pulumi:"status"`
	// Hidden setting index of Syslog.
	SyslogType *int `pulumi:"syslogType"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

type LogSyslogdOverrideSettingState struct {
	// Certificate used to communicate with Syslog server.
	Certificate pulumi.StringPtrInput
	// Custom field name for CEF format logging. The structure of `customFieldName` block is documented below.
	CustomFieldNames LogSyslogdOverrideSettingCustomFieldNameArrayInput
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable pulumi.StringPtrInput
	// Enable/disable reliable syslogging with TLS encryption. Valid values: `high-medium`, `high`, `low`, `disable`.
	EncAlgorithm pulumi.StringPtrInput
	// Remote syslog facility. Valid values: `kernel`, `user`, `mail`, `daemon`, `auth`, `syslog`, `lpr`, `news`, `uucp`, `cron`, `authpriv`, `ftp`, `ntp`, `audit`, `alert`, `clock`, `local0`, `local1`, `local2`, `local3`, `local4`, `local5`, `local6`, `local7`.
	Facility pulumi.StringPtrInput
	// Log format.
	Format pulumi.StringPtrInput
	// Specify outgoing interface to reach server.
	Interface pulumi.StringPtrInput
	// Specify how to select outgoing interface to reach server. Valid values: `auto`, `sdwan`, `specify`.
	InterfaceSelectMethod pulumi.StringPtrInput
	// Syslog maximum log rate in MBps (0 = unlimited).
	MaxLogRate pulumi.IntPtrInput
	// Remote syslog logging over UDP/Reliable TCP. Valid values: `udp`, `legacy-reliable`, `reliable`.
	Mode pulumi.StringPtrInput
	// Enable/disable override syslog settings. Valid values: `enable`, `disable`.
	Override pulumi.StringPtrInput
	// Server listen port.
	Port pulumi.IntPtrInput
	// Set log transmission priority. Valid values: `default`, `low`.
	Priority pulumi.StringPtrInput
	// Address of remote syslog server.
	Server pulumi.StringPtrInput
	// Source IP address of syslog.
	SourceIp pulumi.StringPtrInput
	// Minimum supported protocol version for SSL/TLS connections (default is to follow system global setting). Valid values: `default`, `SSLv3`, `TLSv1`, `TLSv1-1`, `TLSv1-2`.
	SslMinProtoVersion pulumi.StringPtrInput
	// Enable/disable remote syslog logging. Valid values: `enable`, `disable`.
	Status pulumi.StringPtrInput
	// Hidden setting index of Syslog.
	SyslogType pulumi.IntPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (LogSyslogdOverrideSettingState) ElementType() reflect.Type {
	return reflect.TypeOf((*logSyslogdOverrideSettingState)(nil)).Elem()
}

type logSyslogdOverrideSettingArgs struct {
	// Certificate used to communicate with Syslog server.
	Certificate *string `pulumi:"certificate"`
	// Custom field name for CEF format logging. The structure of `customFieldName` block is documented below.
	CustomFieldNames []LogSyslogdOverrideSettingCustomFieldName `pulumi:"customFieldNames"`
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable *string `pulumi:"dynamicSortSubtable"`
	// Enable/disable reliable syslogging with TLS encryption. Valid values: `high-medium`, `high`, `low`, `disable`.
	EncAlgorithm *string `pulumi:"encAlgorithm"`
	// Remote syslog facility. Valid values: `kernel`, `user`, `mail`, `daemon`, `auth`, `syslog`, `lpr`, `news`, `uucp`, `cron`, `authpriv`, `ftp`, `ntp`, `audit`, `alert`, `clock`, `local0`, `local1`, `local2`, `local3`, `local4`, `local5`, `local6`, `local7`.
	Facility *string `pulumi:"facility"`
	// Log format.
	Format *string `pulumi:"format"`
	// Specify outgoing interface to reach server.
	Interface *string `pulumi:"interface"`
	// Specify how to select outgoing interface to reach server. Valid values: `auto`, `sdwan`, `specify`.
	InterfaceSelectMethod *string `pulumi:"interfaceSelectMethod"`
	// Syslog maximum log rate in MBps (0 = unlimited).
	MaxLogRate *int `pulumi:"maxLogRate"`
	// Remote syslog logging over UDP/Reliable TCP. Valid values: `udp`, `legacy-reliable`, `reliable`.
	Mode *string `pulumi:"mode"`
	// Enable/disable override syslog settings. Valid values: `enable`, `disable`.
	Override *string `pulumi:"override"`
	// Server listen port.
	Port *int `pulumi:"port"`
	// Set log transmission priority. Valid values: `default`, `low`.
	Priority *string `pulumi:"priority"`
	// Address of remote syslog server.
	Server *string `pulumi:"server"`
	// Source IP address of syslog.
	SourceIp *string `pulumi:"sourceIp"`
	// Minimum supported protocol version for SSL/TLS connections (default is to follow system global setting). Valid values: `default`, `SSLv3`, `TLSv1`, `TLSv1-1`, `TLSv1-2`.
	SslMinProtoVersion *string `pulumi:"sslMinProtoVersion"`
	// Enable/disable remote syslog logging. Valid values: `enable`, `disable`.
	Status *string `pulumi:"status"`
	// Hidden setting index of Syslog.
	SyslogType *int `pulumi:"syslogType"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

// The set of arguments for constructing a LogSyslogdOverrideSetting resource.
type LogSyslogdOverrideSettingArgs struct {
	// Certificate used to communicate with Syslog server.
	Certificate pulumi.StringPtrInput
	// Custom field name for CEF format logging. The structure of `customFieldName` block is documented below.
	CustomFieldNames LogSyslogdOverrideSettingCustomFieldNameArrayInput
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable pulumi.StringPtrInput
	// Enable/disable reliable syslogging with TLS encryption. Valid values: `high-medium`, `high`, `low`, `disable`.
	EncAlgorithm pulumi.StringPtrInput
	// Remote syslog facility. Valid values: `kernel`, `user`, `mail`, `daemon`, `auth`, `syslog`, `lpr`, `news`, `uucp`, `cron`, `authpriv`, `ftp`, `ntp`, `audit`, `alert`, `clock`, `local0`, `local1`, `local2`, `local3`, `local4`, `local5`, `local6`, `local7`.
	Facility pulumi.StringPtrInput
	// Log format.
	Format pulumi.StringPtrInput
	// Specify outgoing interface to reach server.
	Interface pulumi.StringPtrInput
	// Specify how to select outgoing interface to reach server. Valid values: `auto`, `sdwan`, `specify`.
	InterfaceSelectMethod pulumi.StringPtrInput
	// Syslog maximum log rate in MBps (0 = unlimited).
	MaxLogRate pulumi.IntPtrInput
	// Remote syslog logging over UDP/Reliable TCP. Valid values: `udp`, `legacy-reliable`, `reliable`.
	Mode pulumi.StringPtrInput
	// Enable/disable override syslog settings. Valid values: `enable`, `disable`.
	Override pulumi.StringPtrInput
	// Server listen port.
	Port pulumi.IntPtrInput
	// Set log transmission priority. Valid values: `default`, `low`.
	Priority pulumi.StringPtrInput
	// Address of remote syslog server.
	Server pulumi.StringPtrInput
	// Source IP address of syslog.
	SourceIp pulumi.StringPtrInput
	// Minimum supported protocol version for SSL/TLS connections (default is to follow system global setting). Valid values: `default`, `SSLv3`, `TLSv1`, `TLSv1-1`, `TLSv1-2`.
	SslMinProtoVersion pulumi.StringPtrInput
	// Enable/disable remote syslog logging. Valid values: `enable`, `disable`.
	Status pulumi.StringPtrInput
	// Hidden setting index of Syslog.
	SyslogType pulumi.IntPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (LogSyslogdOverrideSettingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*logSyslogdOverrideSettingArgs)(nil)).Elem()
}

type LogSyslogdOverrideSettingInput interface {
	pulumi.Input

	ToLogSyslogdOverrideSettingOutput() LogSyslogdOverrideSettingOutput
	ToLogSyslogdOverrideSettingOutputWithContext(ctx context.Context) LogSyslogdOverrideSettingOutput
}

func (*LogSyslogdOverrideSetting) ElementType() reflect.Type {
	return reflect.TypeOf((**LogSyslogdOverrideSetting)(nil)).Elem()
}

func (i *LogSyslogdOverrideSetting) ToLogSyslogdOverrideSettingOutput() LogSyslogdOverrideSettingOutput {
	return i.ToLogSyslogdOverrideSettingOutputWithContext(context.Background())
}

func (i *LogSyslogdOverrideSetting) ToLogSyslogdOverrideSettingOutputWithContext(ctx context.Context) LogSyslogdOverrideSettingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogSyslogdOverrideSettingOutput)
}

// LogSyslogdOverrideSettingArrayInput is an input type that accepts LogSyslogdOverrideSettingArray and LogSyslogdOverrideSettingArrayOutput values.
// You can construct a concrete instance of `LogSyslogdOverrideSettingArrayInput` via:
//
//          LogSyslogdOverrideSettingArray{ LogSyslogdOverrideSettingArgs{...} }
type LogSyslogdOverrideSettingArrayInput interface {
	pulumi.Input

	ToLogSyslogdOverrideSettingArrayOutput() LogSyslogdOverrideSettingArrayOutput
	ToLogSyslogdOverrideSettingArrayOutputWithContext(context.Context) LogSyslogdOverrideSettingArrayOutput
}

type LogSyslogdOverrideSettingArray []LogSyslogdOverrideSettingInput

func (LogSyslogdOverrideSettingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LogSyslogdOverrideSetting)(nil)).Elem()
}

func (i LogSyslogdOverrideSettingArray) ToLogSyslogdOverrideSettingArrayOutput() LogSyslogdOverrideSettingArrayOutput {
	return i.ToLogSyslogdOverrideSettingArrayOutputWithContext(context.Background())
}

func (i LogSyslogdOverrideSettingArray) ToLogSyslogdOverrideSettingArrayOutputWithContext(ctx context.Context) LogSyslogdOverrideSettingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogSyslogdOverrideSettingArrayOutput)
}

// LogSyslogdOverrideSettingMapInput is an input type that accepts LogSyslogdOverrideSettingMap and LogSyslogdOverrideSettingMapOutput values.
// You can construct a concrete instance of `LogSyslogdOverrideSettingMapInput` via:
//
//          LogSyslogdOverrideSettingMap{ "key": LogSyslogdOverrideSettingArgs{...} }
type LogSyslogdOverrideSettingMapInput interface {
	pulumi.Input

	ToLogSyslogdOverrideSettingMapOutput() LogSyslogdOverrideSettingMapOutput
	ToLogSyslogdOverrideSettingMapOutputWithContext(context.Context) LogSyslogdOverrideSettingMapOutput
}

type LogSyslogdOverrideSettingMap map[string]LogSyslogdOverrideSettingInput

func (LogSyslogdOverrideSettingMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LogSyslogdOverrideSetting)(nil)).Elem()
}

func (i LogSyslogdOverrideSettingMap) ToLogSyslogdOverrideSettingMapOutput() LogSyslogdOverrideSettingMapOutput {
	return i.ToLogSyslogdOverrideSettingMapOutputWithContext(context.Background())
}

func (i LogSyslogdOverrideSettingMap) ToLogSyslogdOverrideSettingMapOutputWithContext(ctx context.Context) LogSyslogdOverrideSettingMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogSyslogdOverrideSettingMapOutput)
}

type LogSyslogdOverrideSettingOutput struct{ *pulumi.OutputState }

func (LogSyslogdOverrideSettingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LogSyslogdOverrideSetting)(nil)).Elem()
}

func (o LogSyslogdOverrideSettingOutput) ToLogSyslogdOverrideSettingOutput() LogSyslogdOverrideSettingOutput {
	return o
}

func (o LogSyslogdOverrideSettingOutput) ToLogSyslogdOverrideSettingOutputWithContext(ctx context.Context) LogSyslogdOverrideSettingOutput {
	return o
}

type LogSyslogdOverrideSettingArrayOutput struct{ *pulumi.OutputState }

func (LogSyslogdOverrideSettingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LogSyslogdOverrideSetting)(nil)).Elem()
}

func (o LogSyslogdOverrideSettingArrayOutput) ToLogSyslogdOverrideSettingArrayOutput() LogSyslogdOverrideSettingArrayOutput {
	return o
}

func (o LogSyslogdOverrideSettingArrayOutput) ToLogSyslogdOverrideSettingArrayOutputWithContext(ctx context.Context) LogSyslogdOverrideSettingArrayOutput {
	return o
}

func (o LogSyslogdOverrideSettingArrayOutput) Index(i pulumi.IntInput) LogSyslogdOverrideSettingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *LogSyslogdOverrideSetting {
		return vs[0].([]*LogSyslogdOverrideSetting)[vs[1].(int)]
	}).(LogSyslogdOverrideSettingOutput)
}

type LogSyslogdOverrideSettingMapOutput struct{ *pulumi.OutputState }

func (LogSyslogdOverrideSettingMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LogSyslogdOverrideSetting)(nil)).Elem()
}

func (o LogSyslogdOverrideSettingMapOutput) ToLogSyslogdOverrideSettingMapOutput() LogSyslogdOverrideSettingMapOutput {
	return o
}

func (o LogSyslogdOverrideSettingMapOutput) ToLogSyslogdOverrideSettingMapOutputWithContext(ctx context.Context) LogSyslogdOverrideSettingMapOutput {
	return o
}

func (o LogSyslogdOverrideSettingMapOutput) MapIndex(k pulumi.StringInput) LogSyslogdOverrideSettingOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *LogSyslogdOverrideSetting {
		return vs[0].(map[string]*LogSyslogdOverrideSetting)[vs[1].(string)]
	}).(LogSyslogdOverrideSettingOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LogSyslogdOverrideSettingInput)(nil)).Elem(), &LogSyslogdOverrideSetting{})
	pulumi.RegisterInputType(reflect.TypeOf((*LogSyslogdOverrideSettingArrayInput)(nil)).Elem(), LogSyslogdOverrideSettingArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*LogSyslogdOverrideSettingMapInput)(nil)).Elem(), LogSyslogdOverrideSettingMap{})
	pulumi.RegisterOutputType(LogSyslogdOverrideSettingOutput{})
	pulumi.RegisterOutputType(LogSyslogdOverrideSettingArrayOutput{})
	pulumi.RegisterOutputType(LogSyslogdOverrideSettingMapOutput{})
}
