// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Configure FortiSwitch QoS policy.
//
// ## Import
//
// SwitchControllerQos QosPolicy can be imported using any of these accepted formats
//
// ```sh
//  $ pulumi import fortios:index/switchControllerQosQosPolicy:SwitchControllerQosQosPolicy labelname {{name}}
// ```
//
//  If you do not want to import arguments of block$ export "FORTIOS_IMPORT_TABLE"="false"
//
// ```sh
//  $ pulumi import fortios:index/switchControllerQosQosPolicy:SwitchControllerQosQosPolicy labelname {{name}}
// ```
//
//  $ unset "FORTIOS_IMPORT_TABLE"
type SwitchControllerQosQosPolicy struct {
	pulumi.CustomResourceState

	// Default cos queue for untagged packets.
	DefaultCos pulumi.IntOutput `pulumi:"defaultCos"`
	// QoS policy name.
	Name pulumi.StringOutput `pulumi:"name"`
	// QoS egress queue policy.
	QueuePolicy pulumi.StringOutput `pulumi:"queuePolicy"`
	// QoS trust 802.1p map.
	TrustDot1pMap pulumi.StringOutput `pulumi:"trustDot1pMap"`
	// QoS trust ip dscp map.
	TrustIpDscpMap pulumi.StringOutput `pulumi:"trustIpDscpMap"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrOutput `pulumi:"vdomparam"`
}

// NewSwitchControllerQosQosPolicy registers a new resource with the given unique name, arguments, and options.
func NewSwitchControllerQosQosPolicy(ctx *pulumi.Context,
	name string, args *SwitchControllerQosQosPolicyArgs, opts ...pulumi.ResourceOption) (*SwitchControllerQosQosPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DefaultCos == nil {
		return nil, errors.New("invalid value for required argument 'DefaultCos'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource SwitchControllerQosQosPolicy
	err := ctx.RegisterResource("fortios:index/switchControllerQosQosPolicy:SwitchControllerQosQosPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSwitchControllerQosQosPolicy gets an existing SwitchControllerQosQosPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSwitchControllerQosQosPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SwitchControllerQosQosPolicyState, opts ...pulumi.ResourceOption) (*SwitchControllerQosQosPolicy, error) {
	var resource SwitchControllerQosQosPolicy
	err := ctx.ReadResource("fortios:index/switchControllerQosQosPolicy:SwitchControllerQosQosPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SwitchControllerQosQosPolicy resources.
type switchControllerQosQosPolicyState struct {
	// Default cos queue for untagged packets.
	DefaultCos *int `pulumi:"defaultCos"`
	// QoS policy name.
	Name *string `pulumi:"name"`
	// QoS egress queue policy.
	QueuePolicy *string `pulumi:"queuePolicy"`
	// QoS trust 802.1p map.
	TrustDot1pMap *string `pulumi:"trustDot1pMap"`
	// QoS trust ip dscp map.
	TrustIpDscpMap *string `pulumi:"trustIpDscpMap"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

type SwitchControllerQosQosPolicyState struct {
	// Default cos queue for untagged packets.
	DefaultCos pulumi.IntPtrInput
	// QoS policy name.
	Name pulumi.StringPtrInput
	// QoS egress queue policy.
	QueuePolicy pulumi.StringPtrInput
	// QoS trust 802.1p map.
	TrustDot1pMap pulumi.StringPtrInput
	// QoS trust ip dscp map.
	TrustIpDscpMap pulumi.StringPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (SwitchControllerQosQosPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*switchControllerQosQosPolicyState)(nil)).Elem()
}

type switchControllerQosQosPolicyArgs struct {
	// Default cos queue for untagged packets.
	DefaultCos int `pulumi:"defaultCos"`
	// QoS policy name.
	Name *string `pulumi:"name"`
	// QoS egress queue policy.
	QueuePolicy *string `pulumi:"queuePolicy"`
	// QoS trust 802.1p map.
	TrustDot1pMap *string `pulumi:"trustDot1pMap"`
	// QoS trust ip dscp map.
	TrustIpDscpMap *string `pulumi:"trustIpDscpMap"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

// The set of arguments for constructing a SwitchControllerQosQosPolicy resource.
type SwitchControllerQosQosPolicyArgs struct {
	// Default cos queue for untagged packets.
	DefaultCos pulumi.IntInput
	// QoS policy name.
	Name pulumi.StringPtrInput
	// QoS egress queue policy.
	QueuePolicy pulumi.StringPtrInput
	// QoS trust 802.1p map.
	TrustDot1pMap pulumi.StringPtrInput
	// QoS trust ip dscp map.
	TrustIpDscpMap pulumi.StringPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (SwitchControllerQosQosPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*switchControllerQosQosPolicyArgs)(nil)).Elem()
}

type SwitchControllerQosQosPolicyInput interface {
	pulumi.Input

	ToSwitchControllerQosQosPolicyOutput() SwitchControllerQosQosPolicyOutput
	ToSwitchControllerQosQosPolicyOutputWithContext(ctx context.Context) SwitchControllerQosQosPolicyOutput
}

func (*SwitchControllerQosQosPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**SwitchControllerQosQosPolicy)(nil)).Elem()
}

func (i *SwitchControllerQosQosPolicy) ToSwitchControllerQosQosPolicyOutput() SwitchControllerQosQosPolicyOutput {
	return i.ToSwitchControllerQosQosPolicyOutputWithContext(context.Background())
}

func (i *SwitchControllerQosQosPolicy) ToSwitchControllerQosQosPolicyOutputWithContext(ctx context.Context) SwitchControllerQosQosPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchControllerQosQosPolicyOutput)
}

// SwitchControllerQosQosPolicyArrayInput is an input type that accepts SwitchControllerQosQosPolicyArray and SwitchControllerQosQosPolicyArrayOutput values.
// You can construct a concrete instance of `SwitchControllerQosQosPolicyArrayInput` via:
//
//          SwitchControllerQosQosPolicyArray{ SwitchControllerQosQosPolicyArgs{...} }
type SwitchControllerQosQosPolicyArrayInput interface {
	pulumi.Input

	ToSwitchControllerQosQosPolicyArrayOutput() SwitchControllerQosQosPolicyArrayOutput
	ToSwitchControllerQosQosPolicyArrayOutputWithContext(context.Context) SwitchControllerQosQosPolicyArrayOutput
}

type SwitchControllerQosQosPolicyArray []SwitchControllerQosQosPolicyInput

func (SwitchControllerQosQosPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SwitchControllerQosQosPolicy)(nil)).Elem()
}

func (i SwitchControllerQosQosPolicyArray) ToSwitchControllerQosQosPolicyArrayOutput() SwitchControllerQosQosPolicyArrayOutput {
	return i.ToSwitchControllerQosQosPolicyArrayOutputWithContext(context.Background())
}

func (i SwitchControllerQosQosPolicyArray) ToSwitchControllerQosQosPolicyArrayOutputWithContext(ctx context.Context) SwitchControllerQosQosPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchControllerQosQosPolicyArrayOutput)
}

// SwitchControllerQosQosPolicyMapInput is an input type that accepts SwitchControllerQosQosPolicyMap and SwitchControllerQosQosPolicyMapOutput values.
// You can construct a concrete instance of `SwitchControllerQosQosPolicyMapInput` via:
//
//          SwitchControllerQosQosPolicyMap{ "key": SwitchControllerQosQosPolicyArgs{...} }
type SwitchControllerQosQosPolicyMapInput interface {
	pulumi.Input

	ToSwitchControllerQosQosPolicyMapOutput() SwitchControllerQosQosPolicyMapOutput
	ToSwitchControllerQosQosPolicyMapOutputWithContext(context.Context) SwitchControllerQosQosPolicyMapOutput
}

type SwitchControllerQosQosPolicyMap map[string]SwitchControllerQosQosPolicyInput

func (SwitchControllerQosQosPolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SwitchControllerQosQosPolicy)(nil)).Elem()
}

func (i SwitchControllerQosQosPolicyMap) ToSwitchControllerQosQosPolicyMapOutput() SwitchControllerQosQosPolicyMapOutput {
	return i.ToSwitchControllerQosQosPolicyMapOutputWithContext(context.Background())
}

func (i SwitchControllerQosQosPolicyMap) ToSwitchControllerQosQosPolicyMapOutputWithContext(ctx context.Context) SwitchControllerQosQosPolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchControllerQosQosPolicyMapOutput)
}

type SwitchControllerQosQosPolicyOutput struct{ *pulumi.OutputState }

func (SwitchControllerQosQosPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SwitchControllerQosQosPolicy)(nil)).Elem()
}

func (o SwitchControllerQosQosPolicyOutput) ToSwitchControllerQosQosPolicyOutput() SwitchControllerQosQosPolicyOutput {
	return o
}

func (o SwitchControllerQosQosPolicyOutput) ToSwitchControllerQosQosPolicyOutputWithContext(ctx context.Context) SwitchControllerQosQosPolicyOutput {
	return o
}

type SwitchControllerQosQosPolicyArrayOutput struct{ *pulumi.OutputState }

func (SwitchControllerQosQosPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SwitchControllerQosQosPolicy)(nil)).Elem()
}

func (o SwitchControllerQosQosPolicyArrayOutput) ToSwitchControllerQosQosPolicyArrayOutput() SwitchControllerQosQosPolicyArrayOutput {
	return o
}

func (o SwitchControllerQosQosPolicyArrayOutput) ToSwitchControllerQosQosPolicyArrayOutputWithContext(ctx context.Context) SwitchControllerQosQosPolicyArrayOutput {
	return o
}

func (o SwitchControllerQosQosPolicyArrayOutput) Index(i pulumi.IntInput) SwitchControllerQosQosPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SwitchControllerQosQosPolicy {
		return vs[0].([]*SwitchControllerQosQosPolicy)[vs[1].(int)]
	}).(SwitchControllerQosQosPolicyOutput)
}

type SwitchControllerQosQosPolicyMapOutput struct{ *pulumi.OutputState }

func (SwitchControllerQosQosPolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SwitchControllerQosQosPolicy)(nil)).Elem()
}

func (o SwitchControllerQosQosPolicyMapOutput) ToSwitchControllerQosQosPolicyMapOutput() SwitchControllerQosQosPolicyMapOutput {
	return o
}

func (o SwitchControllerQosQosPolicyMapOutput) ToSwitchControllerQosQosPolicyMapOutputWithContext(ctx context.Context) SwitchControllerQosQosPolicyMapOutput {
	return o
}

func (o SwitchControllerQosQosPolicyMapOutput) MapIndex(k pulumi.StringInput) SwitchControllerQosQosPolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SwitchControllerQosQosPolicy {
		return vs[0].(map[string]*SwitchControllerQosQosPolicy)[vs[1].(string)]
	}).(SwitchControllerQosQosPolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchControllerQosQosPolicyInput)(nil)).Elem(), &SwitchControllerQosQosPolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchControllerQosQosPolicyArrayInput)(nil)).Elem(), SwitchControllerQosQosPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchControllerQosQosPolicyMapInput)(nil)).Elem(), SwitchControllerQosQosPolicyMap{})
	pulumi.RegisterOutputType(SwitchControllerQosQosPolicyOutput{})
	pulumi.RegisterOutputType(SwitchControllerQosQosPolicyArrayOutput{})
	pulumi.RegisterOutputType(SwitchControllerQosQosPolicyMapOutput{})
}
