// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Configure VDOM property.
//
// ## Import
//
// System VdomProperty can be imported using any of these accepted formats$ export "FORTIOS_IMPORT_TABLE"="true"
//
// ```sh
//  $ pulumi import fortios:index/systemVdomProperty:SystemVdomProperty labelname {{name}}
// ```
//
//  $ unset "FORTIOS_IMPORT_TABLE"
type SystemVdomProperty struct {
	pulumi.CustomResourceState

	// Maximum guaranteed number of firewall custom services.
	CustomService pulumi.StringOutput `pulumi:"customService"`
	// Description.
	Description pulumi.StringOutput `pulumi:"description"`
	// Maximum guaranteed number of dial-up tunnels.
	DialupTunnel pulumi.StringOutput `pulumi:"dialupTunnel"`
	// Maximum guaranteed number of firewall addresses (IPv4, IPv6, multicast).
	FirewallAddress pulumi.StringOutput `pulumi:"firewallAddress"`
	// Maximum guaranteed number of firewall address groups (IPv4, IPv6).
	FirewallAddrgrp pulumi.StringOutput `pulumi:"firewallAddrgrp"`
	// Maximum guaranteed number of firewall policies (IPv4, IPv6, policy46, policy64, DoS-policy4, DoS-policy6, multicast).
	FirewallPolicy pulumi.StringOutput `pulumi:"firewallPolicy"`
	// Maximum guaranteed number of VPN IPsec phase 1 tunnels.
	IpsecPhase1 pulumi.StringOutput `pulumi:"ipsecPhase1"`
	// Maximum guaranteed number of VPN IPsec phase1 interface tunnels.
	IpsecPhase1Interface pulumi.StringOutput `pulumi:"ipsecPhase1Interface"`
	// Maximum guaranteed number of VPN IPsec phase 2 tunnels.
	IpsecPhase2 pulumi.StringOutput `pulumi:"ipsecPhase2"`
	// Maximum guaranteed number of VPN IPsec phase2 interface tunnels.
	IpsecPhase2Interface pulumi.StringOutput `pulumi:"ipsecPhase2Interface"`
	// Log disk quota in MB (range depends on how much disk space is available).
	LogDiskQuota pulumi.StringOutput `pulumi:"logDiskQuota"`
	// VDOM name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Maximum guaranteed number of firewall one-time schedules.
	OnetimeSchedule pulumi.StringOutput `pulumi:"onetimeSchedule"`
	// Maximum guaranteed number of concurrent proxy users.
	Proxy pulumi.StringOutput `pulumi:"proxy"`
	// Maximum guaranteed number of firewall recurring schedules.
	RecurringSchedule pulumi.StringOutput `pulumi:"recurringSchedule"`
	// Maximum guaranteed number of firewall service groups.
	ServiceGroup pulumi.StringOutput `pulumi:"serviceGroup"`
	// Maximum guaranteed number of sessions.
	Session pulumi.StringOutput `pulumi:"session"`
	// Permanent SNMP Index of the virtual domain (0 - 4294967295).
	SnmpIndex pulumi.IntOutput `pulumi:"snmpIndex"`
	// Maximum guaranteed number of SSL-VPNs.
	Sslvpn pulumi.StringOutput `pulumi:"sslvpn"`
	// Maximum guaranteed number of local users.
	User pulumi.StringOutput `pulumi:"user"`
	// Maximum guaranteed number of user groups.
	UserGroup pulumi.StringOutput `pulumi:"userGroup"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrOutput `pulumi:"vdomparam"`
}

// NewSystemVdomProperty registers a new resource with the given unique name, arguments, and options.
func NewSystemVdomProperty(ctx *pulumi.Context,
	name string, args *SystemVdomPropertyArgs, opts ...pulumi.ResourceOption) (*SystemVdomProperty, error) {
	if args == nil {
		args = &SystemVdomPropertyArgs{}
	}

	opts = pkgResourceDefaultOpts(opts)
	var resource SystemVdomProperty
	err := ctx.RegisterResource("fortios:index/systemVdomProperty:SystemVdomProperty", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSystemVdomProperty gets an existing SystemVdomProperty resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSystemVdomProperty(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SystemVdomPropertyState, opts ...pulumi.ResourceOption) (*SystemVdomProperty, error) {
	var resource SystemVdomProperty
	err := ctx.ReadResource("fortios:index/systemVdomProperty:SystemVdomProperty", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SystemVdomProperty resources.
type systemVdomPropertyState struct {
	// Maximum guaranteed number of firewall custom services.
	CustomService *string `pulumi:"customService"`
	// Description.
	Description *string `pulumi:"description"`
	// Maximum guaranteed number of dial-up tunnels.
	DialupTunnel *string `pulumi:"dialupTunnel"`
	// Maximum guaranteed number of firewall addresses (IPv4, IPv6, multicast).
	FirewallAddress *string `pulumi:"firewallAddress"`
	// Maximum guaranteed number of firewall address groups (IPv4, IPv6).
	FirewallAddrgrp *string `pulumi:"firewallAddrgrp"`
	// Maximum guaranteed number of firewall policies (IPv4, IPv6, policy46, policy64, DoS-policy4, DoS-policy6, multicast).
	FirewallPolicy *string `pulumi:"firewallPolicy"`
	// Maximum guaranteed number of VPN IPsec phase 1 tunnels.
	IpsecPhase1 *string `pulumi:"ipsecPhase1"`
	// Maximum guaranteed number of VPN IPsec phase1 interface tunnels.
	IpsecPhase1Interface *string `pulumi:"ipsecPhase1Interface"`
	// Maximum guaranteed number of VPN IPsec phase 2 tunnels.
	IpsecPhase2 *string `pulumi:"ipsecPhase2"`
	// Maximum guaranteed number of VPN IPsec phase2 interface tunnels.
	IpsecPhase2Interface *string `pulumi:"ipsecPhase2Interface"`
	// Log disk quota in MB (range depends on how much disk space is available).
	LogDiskQuota *string `pulumi:"logDiskQuota"`
	// VDOM name.
	Name *string `pulumi:"name"`
	// Maximum guaranteed number of firewall one-time schedules.
	OnetimeSchedule *string `pulumi:"onetimeSchedule"`
	// Maximum guaranteed number of concurrent proxy users.
	Proxy *string `pulumi:"proxy"`
	// Maximum guaranteed number of firewall recurring schedules.
	RecurringSchedule *string `pulumi:"recurringSchedule"`
	// Maximum guaranteed number of firewall service groups.
	ServiceGroup *string `pulumi:"serviceGroup"`
	// Maximum guaranteed number of sessions.
	Session *string `pulumi:"session"`
	// Permanent SNMP Index of the virtual domain (0 - 4294967295).
	SnmpIndex *int `pulumi:"snmpIndex"`
	// Maximum guaranteed number of SSL-VPNs.
	Sslvpn *string `pulumi:"sslvpn"`
	// Maximum guaranteed number of local users.
	User *string `pulumi:"user"`
	// Maximum guaranteed number of user groups.
	UserGroup *string `pulumi:"userGroup"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

type SystemVdomPropertyState struct {
	// Maximum guaranteed number of firewall custom services.
	CustomService pulumi.StringPtrInput
	// Description.
	Description pulumi.StringPtrInput
	// Maximum guaranteed number of dial-up tunnels.
	DialupTunnel pulumi.StringPtrInput
	// Maximum guaranteed number of firewall addresses (IPv4, IPv6, multicast).
	FirewallAddress pulumi.StringPtrInput
	// Maximum guaranteed number of firewall address groups (IPv4, IPv6).
	FirewallAddrgrp pulumi.StringPtrInput
	// Maximum guaranteed number of firewall policies (IPv4, IPv6, policy46, policy64, DoS-policy4, DoS-policy6, multicast).
	FirewallPolicy pulumi.StringPtrInput
	// Maximum guaranteed number of VPN IPsec phase 1 tunnels.
	IpsecPhase1 pulumi.StringPtrInput
	// Maximum guaranteed number of VPN IPsec phase1 interface tunnels.
	IpsecPhase1Interface pulumi.StringPtrInput
	// Maximum guaranteed number of VPN IPsec phase 2 tunnels.
	IpsecPhase2 pulumi.StringPtrInput
	// Maximum guaranteed number of VPN IPsec phase2 interface tunnels.
	IpsecPhase2Interface pulumi.StringPtrInput
	// Log disk quota in MB (range depends on how much disk space is available).
	LogDiskQuota pulumi.StringPtrInput
	// VDOM name.
	Name pulumi.StringPtrInput
	// Maximum guaranteed number of firewall one-time schedules.
	OnetimeSchedule pulumi.StringPtrInput
	// Maximum guaranteed number of concurrent proxy users.
	Proxy pulumi.StringPtrInput
	// Maximum guaranteed number of firewall recurring schedules.
	RecurringSchedule pulumi.StringPtrInput
	// Maximum guaranteed number of firewall service groups.
	ServiceGroup pulumi.StringPtrInput
	// Maximum guaranteed number of sessions.
	Session pulumi.StringPtrInput
	// Permanent SNMP Index of the virtual domain (0 - 4294967295).
	SnmpIndex pulumi.IntPtrInput
	// Maximum guaranteed number of SSL-VPNs.
	Sslvpn pulumi.StringPtrInput
	// Maximum guaranteed number of local users.
	User pulumi.StringPtrInput
	// Maximum guaranteed number of user groups.
	UserGroup pulumi.StringPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (SystemVdomPropertyState) ElementType() reflect.Type {
	return reflect.TypeOf((*systemVdomPropertyState)(nil)).Elem()
}

type systemVdomPropertyArgs struct {
	// Maximum guaranteed number of firewall custom services.
	CustomService *string `pulumi:"customService"`
	// Description.
	Description *string `pulumi:"description"`
	// Maximum guaranteed number of dial-up tunnels.
	DialupTunnel *string `pulumi:"dialupTunnel"`
	// Maximum guaranteed number of firewall addresses (IPv4, IPv6, multicast).
	FirewallAddress *string `pulumi:"firewallAddress"`
	// Maximum guaranteed number of firewall address groups (IPv4, IPv6).
	FirewallAddrgrp *string `pulumi:"firewallAddrgrp"`
	// Maximum guaranteed number of firewall policies (IPv4, IPv6, policy46, policy64, DoS-policy4, DoS-policy6, multicast).
	FirewallPolicy *string `pulumi:"firewallPolicy"`
	// Maximum guaranteed number of VPN IPsec phase 1 tunnels.
	IpsecPhase1 *string `pulumi:"ipsecPhase1"`
	// Maximum guaranteed number of VPN IPsec phase1 interface tunnels.
	IpsecPhase1Interface *string `pulumi:"ipsecPhase1Interface"`
	// Maximum guaranteed number of VPN IPsec phase 2 tunnels.
	IpsecPhase2 *string `pulumi:"ipsecPhase2"`
	// Maximum guaranteed number of VPN IPsec phase2 interface tunnels.
	IpsecPhase2Interface *string `pulumi:"ipsecPhase2Interface"`
	// Log disk quota in MB (range depends on how much disk space is available).
	LogDiskQuota *string `pulumi:"logDiskQuota"`
	// VDOM name.
	Name *string `pulumi:"name"`
	// Maximum guaranteed number of firewall one-time schedules.
	OnetimeSchedule *string `pulumi:"onetimeSchedule"`
	// Maximum guaranteed number of concurrent proxy users.
	Proxy *string `pulumi:"proxy"`
	// Maximum guaranteed number of firewall recurring schedules.
	RecurringSchedule *string `pulumi:"recurringSchedule"`
	// Maximum guaranteed number of firewall service groups.
	ServiceGroup *string `pulumi:"serviceGroup"`
	// Maximum guaranteed number of sessions.
	Session *string `pulumi:"session"`
	// Permanent SNMP Index of the virtual domain (0 - 4294967295).
	SnmpIndex *int `pulumi:"snmpIndex"`
	// Maximum guaranteed number of SSL-VPNs.
	Sslvpn *string `pulumi:"sslvpn"`
	// Maximum guaranteed number of local users.
	User *string `pulumi:"user"`
	// Maximum guaranteed number of user groups.
	UserGroup *string `pulumi:"userGroup"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

// The set of arguments for constructing a SystemVdomProperty resource.
type SystemVdomPropertyArgs struct {
	// Maximum guaranteed number of firewall custom services.
	CustomService pulumi.StringPtrInput
	// Description.
	Description pulumi.StringPtrInput
	// Maximum guaranteed number of dial-up tunnels.
	DialupTunnel pulumi.StringPtrInput
	// Maximum guaranteed number of firewall addresses (IPv4, IPv6, multicast).
	FirewallAddress pulumi.StringPtrInput
	// Maximum guaranteed number of firewall address groups (IPv4, IPv6).
	FirewallAddrgrp pulumi.StringPtrInput
	// Maximum guaranteed number of firewall policies (IPv4, IPv6, policy46, policy64, DoS-policy4, DoS-policy6, multicast).
	FirewallPolicy pulumi.StringPtrInput
	// Maximum guaranteed number of VPN IPsec phase 1 tunnels.
	IpsecPhase1 pulumi.StringPtrInput
	// Maximum guaranteed number of VPN IPsec phase1 interface tunnels.
	IpsecPhase1Interface pulumi.StringPtrInput
	// Maximum guaranteed number of VPN IPsec phase 2 tunnels.
	IpsecPhase2 pulumi.StringPtrInput
	// Maximum guaranteed number of VPN IPsec phase2 interface tunnels.
	IpsecPhase2Interface pulumi.StringPtrInput
	// Log disk quota in MB (range depends on how much disk space is available).
	LogDiskQuota pulumi.StringPtrInput
	// VDOM name.
	Name pulumi.StringPtrInput
	// Maximum guaranteed number of firewall one-time schedules.
	OnetimeSchedule pulumi.StringPtrInput
	// Maximum guaranteed number of concurrent proxy users.
	Proxy pulumi.StringPtrInput
	// Maximum guaranteed number of firewall recurring schedules.
	RecurringSchedule pulumi.StringPtrInput
	// Maximum guaranteed number of firewall service groups.
	ServiceGroup pulumi.StringPtrInput
	// Maximum guaranteed number of sessions.
	Session pulumi.StringPtrInput
	// Permanent SNMP Index of the virtual domain (0 - 4294967295).
	SnmpIndex pulumi.IntPtrInput
	// Maximum guaranteed number of SSL-VPNs.
	Sslvpn pulumi.StringPtrInput
	// Maximum guaranteed number of local users.
	User pulumi.StringPtrInput
	// Maximum guaranteed number of user groups.
	UserGroup pulumi.StringPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (SystemVdomPropertyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*systemVdomPropertyArgs)(nil)).Elem()
}

type SystemVdomPropertyInput interface {
	pulumi.Input

	ToSystemVdomPropertyOutput() SystemVdomPropertyOutput
	ToSystemVdomPropertyOutputWithContext(ctx context.Context) SystemVdomPropertyOutput
}

func (*SystemVdomProperty) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemVdomProperty)(nil)).Elem()
}

func (i *SystemVdomProperty) ToSystemVdomPropertyOutput() SystemVdomPropertyOutput {
	return i.ToSystemVdomPropertyOutputWithContext(context.Background())
}

func (i *SystemVdomProperty) ToSystemVdomPropertyOutputWithContext(ctx context.Context) SystemVdomPropertyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemVdomPropertyOutput)
}

// SystemVdomPropertyArrayInput is an input type that accepts SystemVdomPropertyArray and SystemVdomPropertyArrayOutput values.
// You can construct a concrete instance of `SystemVdomPropertyArrayInput` via:
//
//          SystemVdomPropertyArray{ SystemVdomPropertyArgs{...} }
type SystemVdomPropertyArrayInput interface {
	pulumi.Input

	ToSystemVdomPropertyArrayOutput() SystemVdomPropertyArrayOutput
	ToSystemVdomPropertyArrayOutputWithContext(context.Context) SystemVdomPropertyArrayOutput
}

type SystemVdomPropertyArray []SystemVdomPropertyInput

func (SystemVdomPropertyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SystemVdomProperty)(nil)).Elem()
}

func (i SystemVdomPropertyArray) ToSystemVdomPropertyArrayOutput() SystemVdomPropertyArrayOutput {
	return i.ToSystemVdomPropertyArrayOutputWithContext(context.Background())
}

func (i SystemVdomPropertyArray) ToSystemVdomPropertyArrayOutputWithContext(ctx context.Context) SystemVdomPropertyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemVdomPropertyArrayOutput)
}

// SystemVdomPropertyMapInput is an input type that accepts SystemVdomPropertyMap and SystemVdomPropertyMapOutput values.
// You can construct a concrete instance of `SystemVdomPropertyMapInput` via:
//
//          SystemVdomPropertyMap{ "key": SystemVdomPropertyArgs{...} }
type SystemVdomPropertyMapInput interface {
	pulumi.Input

	ToSystemVdomPropertyMapOutput() SystemVdomPropertyMapOutput
	ToSystemVdomPropertyMapOutputWithContext(context.Context) SystemVdomPropertyMapOutput
}

type SystemVdomPropertyMap map[string]SystemVdomPropertyInput

func (SystemVdomPropertyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SystemVdomProperty)(nil)).Elem()
}

func (i SystemVdomPropertyMap) ToSystemVdomPropertyMapOutput() SystemVdomPropertyMapOutput {
	return i.ToSystemVdomPropertyMapOutputWithContext(context.Background())
}

func (i SystemVdomPropertyMap) ToSystemVdomPropertyMapOutputWithContext(ctx context.Context) SystemVdomPropertyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemVdomPropertyMapOutput)
}

type SystemVdomPropertyOutput struct{ *pulumi.OutputState }

func (SystemVdomPropertyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemVdomProperty)(nil)).Elem()
}

func (o SystemVdomPropertyOutput) ToSystemVdomPropertyOutput() SystemVdomPropertyOutput {
	return o
}

func (o SystemVdomPropertyOutput) ToSystemVdomPropertyOutputWithContext(ctx context.Context) SystemVdomPropertyOutput {
	return o
}

type SystemVdomPropertyArrayOutput struct{ *pulumi.OutputState }

func (SystemVdomPropertyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SystemVdomProperty)(nil)).Elem()
}

func (o SystemVdomPropertyArrayOutput) ToSystemVdomPropertyArrayOutput() SystemVdomPropertyArrayOutput {
	return o
}

func (o SystemVdomPropertyArrayOutput) ToSystemVdomPropertyArrayOutputWithContext(ctx context.Context) SystemVdomPropertyArrayOutput {
	return o
}

func (o SystemVdomPropertyArrayOutput) Index(i pulumi.IntInput) SystemVdomPropertyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SystemVdomProperty {
		return vs[0].([]*SystemVdomProperty)[vs[1].(int)]
	}).(SystemVdomPropertyOutput)
}

type SystemVdomPropertyMapOutput struct{ *pulumi.OutputState }

func (SystemVdomPropertyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SystemVdomProperty)(nil)).Elem()
}

func (o SystemVdomPropertyMapOutput) ToSystemVdomPropertyMapOutput() SystemVdomPropertyMapOutput {
	return o
}

func (o SystemVdomPropertyMapOutput) ToSystemVdomPropertyMapOutputWithContext(ctx context.Context) SystemVdomPropertyMapOutput {
	return o
}

func (o SystemVdomPropertyMapOutput) MapIndex(k pulumi.StringInput) SystemVdomPropertyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SystemVdomProperty {
		return vs[0].(map[string]*SystemVdomProperty)[vs[1].(string)]
	}).(SystemVdomPropertyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SystemVdomPropertyInput)(nil)).Elem(), &SystemVdomProperty{})
	pulumi.RegisterInputType(reflect.TypeOf((*SystemVdomPropertyArrayInput)(nil)).Elem(), SystemVdomPropertyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SystemVdomPropertyMapInput)(nil)).Elem(), SystemVdomPropertyMap{})
	pulumi.RegisterOutputType(SystemVdomPropertyOutput{})
	pulumi.RegisterOutputType(SystemVdomPropertyArrayOutput{})
	pulumi.RegisterOutputType(SystemVdomPropertyMapOutput{})
}
