// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Configure Link Health Monitor.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-fortios/sdk/go/fortios"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := fortios.NewSystemLinkMonitor(ctx, "trname", &fortios.SystemLinkMonitorArgs{
// 			AddrMode:     pulumi.String("ipv4"),
// 			Failtime:     pulumi.Int(5),
// 			GatewayIp:    pulumi.String("2.2.2.2"),
// 			GatewayIp6:   pulumi.String("::"),
// 			HaPriority:   pulumi.Int(1),
// 			HttpAgent:    pulumi.String("Chrome/ Safari/"),
// 			HttpGet:      pulumi.String("/"),
// 			Interval:     pulumi.Int(1),
// 			PacketSize:   pulumi.Int(64),
// 			Port:         pulumi.Int(80),
// 			Protocol:     pulumi.String("ping"),
// 			Recoverytime: pulumi.Int(5),
// 			SecurityMode: pulumi.String("none"),
// 			Servers: fortios.SystemLinkMonitorServerArray{
// 				&fortios.SystemLinkMonitorServerArgs{
// 					Address: pulumi.String("3.3.3.3"),
// 				},
// 			},
// 			SourceIp:               pulumi.String("0.0.0.0"),
// 			SourceIp6:              pulumi.String("::"),
// 			Srcintf:                pulumi.String("port4"),
// 			Status:                 pulumi.String("enable"),
// 			UpdateCascadeInterface: pulumi.String("enable"),
// 			UpdateStaticRoute:      pulumi.String("enable"),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// System LinkMonitor can be imported using any of these accepted formats$ export "FORTIOS_IMPORT_TABLE"="true"
//
// ```sh
//  $ pulumi import fortios:index/systemLinkMonitor:SystemLinkMonitor labelname {{name}}
// ```
//
//  $ unset "FORTIOS_IMPORT_TABLE"
type SystemLinkMonitor struct {
	pulumi.CustomResourceState

	// Address mode (IPv4 or IPv6). Valid values: `ipv4`, `ipv6`.
	AddrMode pulumi.StringOutput `pulumi:"addrMode"`
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable pulumi.StringPtrOutput `pulumi:"dynamicSortSubtable"`
	// Number of retry attempts before the server is considered down (1 - 10, default = 5)
	Failtime pulumi.IntOutput `pulumi:"failtime"`
	// Gateway IP address used to probe the server.
	GatewayIp pulumi.StringOutput `pulumi:"gatewayIp"`
	// Gateway IPv6 address used to probe the server.
	GatewayIp6 pulumi.StringOutput `pulumi:"gatewayIp6"`
	// HA election priority (1 - 50).
	HaPriority pulumi.IntOutput `pulumi:"haPriority"`
	// String in the http-agent field in the HTTP header.
	HttpAgent pulumi.StringOutput `pulumi:"httpAgent"`
	// If you are monitoring an HTML server you can send an HTTP-GET request with a custom string. Use this option to define the string.
	HttpGet pulumi.StringOutput `pulumi:"httpGet"`
	// String that you expect to see in the HTTP-GET requests of the traffic to be monitored.
	HttpMatch pulumi.StringOutput `pulumi:"httpMatch"`
	// Detection interval (1 - 3600 sec, default = 5).
	Interval pulumi.IntOutput `pulumi:"interval"`
	// Link monitor name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Packet size of a twamp test session,
	PacketSize pulumi.IntOutput `pulumi:"packetSize"`
	// Twamp controller password in authentication mode
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// Port number of the traffic to be used to monitor the server.
	Port pulumi.IntOutput `pulumi:"port"`
	// Number of most recent probes that should be used to calculate latency and jitter (5 - 30, default = 30).
	ProbeCount pulumi.IntOutput `pulumi:"probeCount"`
	// Time to wait before a probe packet is considered lost (500 - 5000 msec, default = 500).
	ProbeTimeout pulumi.IntOutput `pulumi:"probeTimeout"`
	// Protocols used to monitor the server.
	Protocol pulumi.StringOutput `pulumi:"protocol"`
	// Number of successful responses received before server is considered recovered (1 - 10, default = 5).
	Recoverytime pulumi.IntOutput `pulumi:"recoverytime"`
	// Twamp controller security mode. Valid values: `none`, `authentication`.
	SecurityMode pulumi.StringOutput `pulumi:"securityMode"`
	// IP address of the server(s) to be monitored. The structure of `server` block is documented below.
	Servers SystemLinkMonitorServerArrayOutput `pulumi:"servers"`
	// Source IP address used in packet to the server.
	SourceIp pulumi.StringOutput `pulumi:"sourceIp"`
	// Source IPv6 address used in packet to the server.
	SourceIp6 pulumi.StringOutput `pulumi:"sourceIp6"`
	// Interface that receives the traffic to be monitored.
	Srcintf pulumi.StringOutput `pulumi:"srcintf"`
	// Enable/disable this link monitor. Valid values: `enable`, `disable`.
	Status pulumi.StringOutput `pulumi:"status"`
	// Enable/disable update cascade interface. Valid values: `enable`, `disable`.
	UpdateCascadeInterface pulumi.StringOutput `pulumi:"updateCascadeInterface"`
	// Enable/disable updating the static route. Valid values: `enable`, `disable`.
	UpdateStaticRoute pulumi.StringOutput `pulumi:"updateStaticRoute"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrOutput `pulumi:"vdomparam"`
}

// NewSystemLinkMonitor registers a new resource with the given unique name, arguments, and options.
func NewSystemLinkMonitor(ctx *pulumi.Context,
	name string, args *SystemLinkMonitorArgs, opts ...pulumi.ResourceOption) (*SystemLinkMonitor, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Servers == nil {
		return nil, errors.New("invalid value for required argument 'Servers'")
	}
	var resource SystemLinkMonitor
	err := ctx.RegisterResource("fortios:index/systemLinkMonitor:SystemLinkMonitor", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSystemLinkMonitor gets an existing SystemLinkMonitor resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSystemLinkMonitor(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SystemLinkMonitorState, opts ...pulumi.ResourceOption) (*SystemLinkMonitor, error) {
	var resource SystemLinkMonitor
	err := ctx.ReadResource("fortios:index/systemLinkMonitor:SystemLinkMonitor", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SystemLinkMonitor resources.
type systemLinkMonitorState struct {
	// Address mode (IPv4 or IPv6). Valid values: `ipv4`, `ipv6`.
	AddrMode *string `pulumi:"addrMode"`
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable *string `pulumi:"dynamicSortSubtable"`
	// Number of retry attempts before the server is considered down (1 - 10, default = 5)
	Failtime *int `pulumi:"failtime"`
	// Gateway IP address used to probe the server.
	GatewayIp *string `pulumi:"gatewayIp"`
	// Gateway IPv6 address used to probe the server.
	GatewayIp6 *string `pulumi:"gatewayIp6"`
	// HA election priority (1 - 50).
	HaPriority *int `pulumi:"haPriority"`
	// String in the http-agent field in the HTTP header.
	HttpAgent *string `pulumi:"httpAgent"`
	// If you are monitoring an HTML server you can send an HTTP-GET request with a custom string. Use this option to define the string.
	HttpGet *string `pulumi:"httpGet"`
	// String that you expect to see in the HTTP-GET requests of the traffic to be monitored.
	HttpMatch *string `pulumi:"httpMatch"`
	// Detection interval (1 - 3600 sec, default = 5).
	Interval *int `pulumi:"interval"`
	// Link monitor name.
	Name *string `pulumi:"name"`
	// Packet size of a twamp test session,
	PacketSize *int `pulumi:"packetSize"`
	// Twamp controller password in authentication mode
	Password *string `pulumi:"password"`
	// Port number of the traffic to be used to monitor the server.
	Port *int `pulumi:"port"`
	// Number of most recent probes that should be used to calculate latency and jitter (5 - 30, default = 30).
	ProbeCount *int `pulumi:"probeCount"`
	// Time to wait before a probe packet is considered lost (500 - 5000 msec, default = 500).
	ProbeTimeout *int `pulumi:"probeTimeout"`
	// Protocols used to monitor the server.
	Protocol *string `pulumi:"protocol"`
	// Number of successful responses received before server is considered recovered (1 - 10, default = 5).
	Recoverytime *int `pulumi:"recoverytime"`
	// Twamp controller security mode. Valid values: `none`, `authentication`.
	SecurityMode *string `pulumi:"securityMode"`
	// IP address of the server(s) to be monitored. The structure of `server` block is documented below.
	Servers []SystemLinkMonitorServer `pulumi:"servers"`
	// Source IP address used in packet to the server.
	SourceIp *string `pulumi:"sourceIp"`
	// Source IPv6 address used in packet to the server.
	SourceIp6 *string `pulumi:"sourceIp6"`
	// Interface that receives the traffic to be monitored.
	Srcintf *string `pulumi:"srcintf"`
	// Enable/disable this link monitor. Valid values: `enable`, `disable`.
	Status *string `pulumi:"status"`
	// Enable/disable update cascade interface. Valid values: `enable`, `disable`.
	UpdateCascadeInterface *string `pulumi:"updateCascadeInterface"`
	// Enable/disable updating the static route. Valid values: `enable`, `disable`.
	UpdateStaticRoute *string `pulumi:"updateStaticRoute"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

type SystemLinkMonitorState struct {
	// Address mode (IPv4 or IPv6). Valid values: `ipv4`, `ipv6`.
	AddrMode pulumi.StringPtrInput
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable pulumi.StringPtrInput
	// Number of retry attempts before the server is considered down (1 - 10, default = 5)
	Failtime pulumi.IntPtrInput
	// Gateway IP address used to probe the server.
	GatewayIp pulumi.StringPtrInput
	// Gateway IPv6 address used to probe the server.
	GatewayIp6 pulumi.StringPtrInput
	// HA election priority (1 - 50).
	HaPriority pulumi.IntPtrInput
	// String in the http-agent field in the HTTP header.
	HttpAgent pulumi.StringPtrInput
	// If you are monitoring an HTML server you can send an HTTP-GET request with a custom string. Use this option to define the string.
	HttpGet pulumi.StringPtrInput
	// String that you expect to see in the HTTP-GET requests of the traffic to be monitored.
	HttpMatch pulumi.StringPtrInput
	// Detection interval (1 - 3600 sec, default = 5).
	Interval pulumi.IntPtrInput
	// Link monitor name.
	Name pulumi.StringPtrInput
	// Packet size of a twamp test session,
	PacketSize pulumi.IntPtrInput
	// Twamp controller password in authentication mode
	Password pulumi.StringPtrInput
	// Port number of the traffic to be used to monitor the server.
	Port pulumi.IntPtrInput
	// Number of most recent probes that should be used to calculate latency and jitter (5 - 30, default = 30).
	ProbeCount pulumi.IntPtrInput
	// Time to wait before a probe packet is considered lost (500 - 5000 msec, default = 500).
	ProbeTimeout pulumi.IntPtrInput
	// Protocols used to monitor the server.
	Protocol pulumi.StringPtrInput
	// Number of successful responses received before server is considered recovered (1 - 10, default = 5).
	Recoverytime pulumi.IntPtrInput
	// Twamp controller security mode. Valid values: `none`, `authentication`.
	SecurityMode pulumi.StringPtrInput
	// IP address of the server(s) to be monitored. The structure of `server` block is documented below.
	Servers SystemLinkMonitorServerArrayInput
	// Source IP address used in packet to the server.
	SourceIp pulumi.StringPtrInput
	// Source IPv6 address used in packet to the server.
	SourceIp6 pulumi.StringPtrInput
	// Interface that receives the traffic to be monitored.
	Srcintf pulumi.StringPtrInput
	// Enable/disable this link monitor. Valid values: `enable`, `disable`.
	Status pulumi.StringPtrInput
	// Enable/disable update cascade interface. Valid values: `enable`, `disable`.
	UpdateCascadeInterface pulumi.StringPtrInput
	// Enable/disable updating the static route. Valid values: `enable`, `disable`.
	UpdateStaticRoute pulumi.StringPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (SystemLinkMonitorState) ElementType() reflect.Type {
	return reflect.TypeOf((*systemLinkMonitorState)(nil)).Elem()
}

type systemLinkMonitorArgs struct {
	// Address mode (IPv4 or IPv6). Valid values: `ipv4`, `ipv6`.
	AddrMode *string `pulumi:"addrMode"`
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable *string `pulumi:"dynamicSortSubtable"`
	// Number of retry attempts before the server is considered down (1 - 10, default = 5)
	Failtime *int `pulumi:"failtime"`
	// Gateway IP address used to probe the server.
	GatewayIp *string `pulumi:"gatewayIp"`
	// Gateway IPv6 address used to probe the server.
	GatewayIp6 *string `pulumi:"gatewayIp6"`
	// HA election priority (1 - 50).
	HaPriority *int `pulumi:"haPriority"`
	// String in the http-agent field in the HTTP header.
	HttpAgent *string `pulumi:"httpAgent"`
	// If you are monitoring an HTML server you can send an HTTP-GET request with a custom string. Use this option to define the string.
	HttpGet *string `pulumi:"httpGet"`
	// String that you expect to see in the HTTP-GET requests of the traffic to be monitored.
	HttpMatch *string `pulumi:"httpMatch"`
	// Detection interval (1 - 3600 sec, default = 5).
	Interval *int `pulumi:"interval"`
	// Link monitor name.
	Name *string `pulumi:"name"`
	// Packet size of a twamp test session,
	PacketSize *int `pulumi:"packetSize"`
	// Twamp controller password in authentication mode
	Password *string `pulumi:"password"`
	// Port number of the traffic to be used to monitor the server.
	Port *int `pulumi:"port"`
	// Number of most recent probes that should be used to calculate latency and jitter (5 - 30, default = 30).
	ProbeCount *int `pulumi:"probeCount"`
	// Time to wait before a probe packet is considered lost (500 - 5000 msec, default = 500).
	ProbeTimeout *int `pulumi:"probeTimeout"`
	// Protocols used to monitor the server.
	Protocol *string `pulumi:"protocol"`
	// Number of successful responses received before server is considered recovered (1 - 10, default = 5).
	Recoverytime *int `pulumi:"recoverytime"`
	// Twamp controller security mode. Valid values: `none`, `authentication`.
	SecurityMode *string `pulumi:"securityMode"`
	// IP address of the server(s) to be monitored. The structure of `server` block is documented below.
	Servers []SystemLinkMonitorServer `pulumi:"servers"`
	// Source IP address used in packet to the server.
	SourceIp *string `pulumi:"sourceIp"`
	// Source IPv6 address used in packet to the server.
	SourceIp6 *string `pulumi:"sourceIp6"`
	// Interface that receives the traffic to be monitored.
	Srcintf *string `pulumi:"srcintf"`
	// Enable/disable this link monitor. Valid values: `enable`, `disable`.
	Status *string `pulumi:"status"`
	// Enable/disable update cascade interface. Valid values: `enable`, `disable`.
	UpdateCascadeInterface *string `pulumi:"updateCascadeInterface"`
	// Enable/disable updating the static route. Valid values: `enable`, `disable`.
	UpdateStaticRoute *string `pulumi:"updateStaticRoute"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

// The set of arguments for constructing a SystemLinkMonitor resource.
type SystemLinkMonitorArgs struct {
	// Address mode (IPv4 or IPv6). Valid values: `ipv4`, `ipv6`.
	AddrMode pulumi.StringPtrInput
	// true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
	DynamicSortSubtable pulumi.StringPtrInput
	// Number of retry attempts before the server is considered down (1 - 10, default = 5)
	Failtime pulumi.IntPtrInput
	// Gateway IP address used to probe the server.
	GatewayIp pulumi.StringPtrInput
	// Gateway IPv6 address used to probe the server.
	GatewayIp6 pulumi.StringPtrInput
	// HA election priority (1 - 50).
	HaPriority pulumi.IntPtrInput
	// String in the http-agent field in the HTTP header.
	HttpAgent pulumi.StringPtrInput
	// If you are monitoring an HTML server you can send an HTTP-GET request with a custom string. Use this option to define the string.
	HttpGet pulumi.StringPtrInput
	// String that you expect to see in the HTTP-GET requests of the traffic to be monitored.
	HttpMatch pulumi.StringPtrInput
	// Detection interval (1 - 3600 sec, default = 5).
	Interval pulumi.IntPtrInput
	// Link monitor name.
	Name pulumi.StringPtrInput
	// Packet size of a twamp test session,
	PacketSize pulumi.IntPtrInput
	// Twamp controller password in authentication mode
	Password pulumi.StringPtrInput
	// Port number of the traffic to be used to monitor the server.
	Port pulumi.IntPtrInput
	// Number of most recent probes that should be used to calculate latency and jitter (5 - 30, default = 30).
	ProbeCount pulumi.IntPtrInput
	// Time to wait before a probe packet is considered lost (500 - 5000 msec, default = 500).
	ProbeTimeout pulumi.IntPtrInput
	// Protocols used to monitor the server.
	Protocol pulumi.StringPtrInput
	// Number of successful responses received before server is considered recovered (1 - 10, default = 5).
	Recoverytime pulumi.IntPtrInput
	// Twamp controller security mode. Valid values: `none`, `authentication`.
	SecurityMode pulumi.StringPtrInput
	// IP address of the server(s) to be monitored. The structure of `server` block is documented below.
	Servers SystemLinkMonitorServerArrayInput
	// Source IP address used in packet to the server.
	SourceIp pulumi.StringPtrInput
	// Source IPv6 address used in packet to the server.
	SourceIp6 pulumi.StringPtrInput
	// Interface that receives the traffic to be monitored.
	Srcintf pulumi.StringPtrInput
	// Enable/disable this link monitor. Valid values: `enable`, `disable`.
	Status pulumi.StringPtrInput
	// Enable/disable update cascade interface. Valid values: `enable`, `disable`.
	UpdateCascadeInterface pulumi.StringPtrInput
	// Enable/disable updating the static route. Valid values: `enable`, `disable`.
	UpdateStaticRoute pulumi.StringPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (SystemLinkMonitorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*systemLinkMonitorArgs)(nil)).Elem()
}

type SystemLinkMonitorInput interface {
	pulumi.Input

	ToSystemLinkMonitorOutput() SystemLinkMonitorOutput
	ToSystemLinkMonitorOutputWithContext(ctx context.Context) SystemLinkMonitorOutput
}

func (*SystemLinkMonitor) ElementType() reflect.Type {
	return reflect.TypeOf((*SystemLinkMonitor)(nil))
}

func (i *SystemLinkMonitor) ToSystemLinkMonitorOutput() SystemLinkMonitorOutput {
	return i.ToSystemLinkMonitorOutputWithContext(context.Background())
}

func (i *SystemLinkMonitor) ToSystemLinkMonitorOutputWithContext(ctx context.Context) SystemLinkMonitorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemLinkMonitorOutput)
}

func (i *SystemLinkMonitor) ToSystemLinkMonitorPtrOutput() SystemLinkMonitorPtrOutput {
	return i.ToSystemLinkMonitorPtrOutputWithContext(context.Background())
}

func (i *SystemLinkMonitor) ToSystemLinkMonitorPtrOutputWithContext(ctx context.Context) SystemLinkMonitorPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemLinkMonitorPtrOutput)
}

type SystemLinkMonitorPtrInput interface {
	pulumi.Input

	ToSystemLinkMonitorPtrOutput() SystemLinkMonitorPtrOutput
	ToSystemLinkMonitorPtrOutputWithContext(ctx context.Context) SystemLinkMonitorPtrOutput
}

type systemLinkMonitorPtrType SystemLinkMonitorArgs

func (*systemLinkMonitorPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemLinkMonitor)(nil))
}

func (i *systemLinkMonitorPtrType) ToSystemLinkMonitorPtrOutput() SystemLinkMonitorPtrOutput {
	return i.ToSystemLinkMonitorPtrOutputWithContext(context.Background())
}

func (i *systemLinkMonitorPtrType) ToSystemLinkMonitorPtrOutputWithContext(ctx context.Context) SystemLinkMonitorPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemLinkMonitorPtrOutput)
}

// SystemLinkMonitorArrayInput is an input type that accepts SystemLinkMonitorArray and SystemLinkMonitorArrayOutput values.
// You can construct a concrete instance of `SystemLinkMonitorArrayInput` via:
//
//          SystemLinkMonitorArray{ SystemLinkMonitorArgs{...} }
type SystemLinkMonitorArrayInput interface {
	pulumi.Input

	ToSystemLinkMonitorArrayOutput() SystemLinkMonitorArrayOutput
	ToSystemLinkMonitorArrayOutputWithContext(context.Context) SystemLinkMonitorArrayOutput
}

type SystemLinkMonitorArray []SystemLinkMonitorInput

func (SystemLinkMonitorArray) ElementType() reflect.Type {
	return reflect.TypeOf(([]*SystemLinkMonitor)(nil))
}

func (i SystemLinkMonitorArray) ToSystemLinkMonitorArrayOutput() SystemLinkMonitorArrayOutput {
	return i.ToSystemLinkMonitorArrayOutputWithContext(context.Background())
}

func (i SystemLinkMonitorArray) ToSystemLinkMonitorArrayOutputWithContext(ctx context.Context) SystemLinkMonitorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemLinkMonitorArrayOutput)
}

// SystemLinkMonitorMapInput is an input type that accepts SystemLinkMonitorMap and SystemLinkMonitorMapOutput values.
// You can construct a concrete instance of `SystemLinkMonitorMapInput` via:
//
//          SystemLinkMonitorMap{ "key": SystemLinkMonitorArgs{...} }
type SystemLinkMonitorMapInput interface {
	pulumi.Input

	ToSystemLinkMonitorMapOutput() SystemLinkMonitorMapOutput
	ToSystemLinkMonitorMapOutputWithContext(context.Context) SystemLinkMonitorMapOutput
}

type SystemLinkMonitorMap map[string]SystemLinkMonitorInput

func (SystemLinkMonitorMap) ElementType() reflect.Type {
	return reflect.TypeOf((map[string]*SystemLinkMonitor)(nil))
}

func (i SystemLinkMonitorMap) ToSystemLinkMonitorMapOutput() SystemLinkMonitorMapOutput {
	return i.ToSystemLinkMonitorMapOutputWithContext(context.Background())
}

func (i SystemLinkMonitorMap) ToSystemLinkMonitorMapOutputWithContext(ctx context.Context) SystemLinkMonitorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemLinkMonitorMapOutput)
}

type SystemLinkMonitorOutput struct {
	*pulumi.OutputState
}

func (SystemLinkMonitorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SystemLinkMonitor)(nil))
}

func (o SystemLinkMonitorOutput) ToSystemLinkMonitorOutput() SystemLinkMonitorOutput {
	return o
}

func (o SystemLinkMonitorOutput) ToSystemLinkMonitorOutputWithContext(ctx context.Context) SystemLinkMonitorOutput {
	return o
}

func (o SystemLinkMonitorOutput) ToSystemLinkMonitorPtrOutput() SystemLinkMonitorPtrOutput {
	return o.ToSystemLinkMonitorPtrOutputWithContext(context.Background())
}

func (o SystemLinkMonitorOutput) ToSystemLinkMonitorPtrOutputWithContext(ctx context.Context) SystemLinkMonitorPtrOutput {
	return o.ApplyT(func(v SystemLinkMonitor) *SystemLinkMonitor {
		return &v
	}).(SystemLinkMonitorPtrOutput)
}

type SystemLinkMonitorPtrOutput struct {
	*pulumi.OutputState
}

func (SystemLinkMonitorPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemLinkMonitor)(nil))
}

func (o SystemLinkMonitorPtrOutput) ToSystemLinkMonitorPtrOutput() SystemLinkMonitorPtrOutput {
	return o
}

func (o SystemLinkMonitorPtrOutput) ToSystemLinkMonitorPtrOutputWithContext(ctx context.Context) SystemLinkMonitorPtrOutput {
	return o
}

type SystemLinkMonitorArrayOutput struct{ *pulumi.OutputState }

func (SystemLinkMonitorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SystemLinkMonitor)(nil))
}

func (o SystemLinkMonitorArrayOutput) ToSystemLinkMonitorArrayOutput() SystemLinkMonitorArrayOutput {
	return o
}

func (o SystemLinkMonitorArrayOutput) ToSystemLinkMonitorArrayOutputWithContext(ctx context.Context) SystemLinkMonitorArrayOutput {
	return o
}

func (o SystemLinkMonitorArrayOutput) Index(i pulumi.IntInput) SystemLinkMonitorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) SystemLinkMonitor {
		return vs[0].([]SystemLinkMonitor)[vs[1].(int)]
	}).(SystemLinkMonitorOutput)
}

type SystemLinkMonitorMapOutput struct{ *pulumi.OutputState }

func (SystemLinkMonitorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]SystemLinkMonitor)(nil))
}

func (o SystemLinkMonitorMapOutput) ToSystemLinkMonitorMapOutput() SystemLinkMonitorMapOutput {
	return o
}

func (o SystemLinkMonitorMapOutput) ToSystemLinkMonitorMapOutputWithContext(ctx context.Context) SystemLinkMonitorMapOutput {
	return o
}

func (o SystemLinkMonitorMapOutput) MapIndex(k pulumi.StringInput) SystemLinkMonitorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) SystemLinkMonitor {
		return vs[0].(map[string]SystemLinkMonitor)[vs[1].(string)]
	}).(SystemLinkMonitorOutput)
}

func init() {
	pulumi.RegisterOutputType(SystemLinkMonitorOutput{})
	pulumi.RegisterOutputType(SystemLinkMonitorPtrOutput{})
	pulumi.RegisterOutputType(SystemLinkMonitorArrayOutput{})
	pulumi.RegisterOutputType(SystemLinkMonitorMapOutput{})
}
