// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"context"
	"reflect"

	"errors"
	"github.com/lubyou/pulumi-fortios/sdk/go/fortios/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SystemAutoupdateSchedule struct {
	pulumi.CustomResourceState

	Day       pulumi.StringOutput    `pulumi:"day"`
	Frequency pulumi.StringOutput    `pulumi:"frequency"`
	Status    pulumi.StringOutput    `pulumi:"status"`
	Time      pulumi.StringOutput    `pulumi:"time"`
	Vdomparam pulumi.StringPtrOutput `pulumi:"vdomparam"`
}

// NewSystemAutoupdateSchedule registers a new resource with the given unique name, arguments, and options.
func NewSystemAutoupdateSchedule(ctx *pulumi.Context,
	name string, args *SystemAutoupdateScheduleArgs, opts ...pulumi.ResourceOption) (*SystemAutoupdateSchedule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Frequency == nil {
		return nil, errors.New("invalid value for required argument 'Frequency'")
	}
	if args.Status == nil {
		return nil, errors.New("invalid value for required argument 'Status'")
	}
	if args.Time == nil {
		return nil, errors.New("invalid value for required argument 'Time'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SystemAutoupdateSchedule
	err := ctx.RegisterResource("fortios:index/systemAutoupdateSchedule:SystemAutoupdateSchedule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSystemAutoupdateSchedule gets an existing SystemAutoupdateSchedule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSystemAutoupdateSchedule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SystemAutoupdateScheduleState, opts ...pulumi.ResourceOption) (*SystemAutoupdateSchedule, error) {
	var resource SystemAutoupdateSchedule
	err := ctx.ReadResource("fortios:index/systemAutoupdateSchedule:SystemAutoupdateSchedule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SystemAutoupdateSchedule resources.
type systemAutoupdateScheduleState struct {
	Day       *string `pulumi:"day"`
	Frequency *string `pulumi:"frequency"`
	Status    *string `pulumi:"status"`
	Time      *string `pulumi:"time"`
	Vdomparam *string `pulumi:"vdomparam"`
}

type SystemAutoupdateScheduleState struct {
	Day       pulumi.StringPtrInput
	Frequency pulumi.StringPtrInput
	Status    pulumi.StringPtrInput
	Time      pulumi.StringPtrInput
	Vdomparam pulumi.StringPtrInput
}

func (SystemAutoupdateScheduleState) ElementType() reflect.Type {
	return reflect.TypeOf((*systemAutoupdateScheduleState)(nil)).Elem()
}

type systemAutoupdateScheduleArgs struct {
	Day       *string `pulumi:"day"`
	Frequency string  `pulumi:"frequency"`
	Status    string  `pulumi:"status"`
	Time      string  `pulumi:"time"`
	Vdomparam *string `pulumi:"vdomparam"`
}

// The set of arguments for constructing a SystemAutoupdateSchedule resource.
type SystemAutoupdateScheduleArgs struct {
	Day       pulumi.StringPtrInput
	Frequency pulumi.StringInput
	Status    pulumi.StringInput
	Time      pulumi.StringInput
	Vdomparam pulumi.StringPtrInput
}

func (SystemAutoupdateScheduleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*systemAutoupdateScheduleArgs)(nil)).Elem()
}

type SystemAutoupdateScheduleInput interface {
	pulumi.Input

	ToSystemAutoupdateScheduleOutput() SystemAutoupdateScheduleOutput
	ToSystemAutoupdateScheduleOutputWithContext(ctx context.Context) SystemAutoupdateScheduleOutput
}

func (*SystemAutoupdateSchedule) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemAutoupdateSchedule)(nil)).Elem()
}

func (i *SystemAutoupdateSchedule) ToSystemAutoupdateScheduleOutput() SystemAutoupdateScheduleOutput {
	return i.ToSystemAutoupdateScheduleOutputWithContext(context.Background())
}

func (i *SystemAutoupdateSchedule) ToSystemAutoupdateScheduleOutputWithContext(ctx context.Context) SystemAutoupdateScheduleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemAutoupdateScheduleOutput)
}

// SystemAutoupdateScheduleArrayInput is an input type that accepts SystemAutoupdateScheduleArray and SystemAutoupdateScheduleArrayOutput values.
// You can construct a concrete instance of `SystemAutoupdateScheduleArrayInput` via:
//
//	SystemAutoupdateScheduleArray{ SystemAutoupdateScheduleArgs{...} }
type SystemAutoupdateScheduleArrayInput interface {
	pulumi.Input

	ToSystemAutoupdateScheduleArrayOutput() SystemAutoupdateScheduleArrayOutput
	ToSystemAutoupdateScheduleArrayOutputWithContext(context.Context) SystemAutoupdateScheduleArrayOutput
}

type SystemAutoupdateScheduleArray []SystemAutoupdateScheduleInput

func (SystemAutoupdateScheduleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SystemAutoupdateSchedule)(nil)).Elem()
}

func (i SystemAutoupdateScheduleArray) ToSystemAutoupdateScheduleArrayOutput() SystemAutoupdateScheduleArrayOutput {
	return i.ToSystemAutoupdateScheduleArrayOutputWithContext(context.Background())
}

func (i SystemAutoupdateScheduleArray) ToSystemAutoupdateScheduleArrayOutputWithContext(ctx context.Context) SystemAutoupdateScheduleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemAutoupdateScheduleArrayOutput)
}

// SystemAutoupdateScheduleMapInput is an input type that accepts SystemAutoupdateScheduleMap and SystemAutoupdateScheduleMapOutput values.
// You can construct a concrete instance of `SystemAutoupdateScheduleMapInput` via:
//
//	SystemAutoupdateScheduleMap{ "key": SystemAutoupdateScheduleArgs{...} }
type SystemAutoupdateScheduleMapInput interface {
	pulumi.Input

	ToSystemAutoupdateScheduleMapOutput() SystemAutoupdateScheduleMapOutput
	ToSystemAutoupdateScheduleMapOutputWithContext(context.Context) SystemAutoupdateScheduleMapOutput
}

type SystemAutoupdateScheduleMap map[string]SystemAutoupdateScheduleInput

func (SystemAutoupdateScheduleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SystemAutoupdateSchedule)(nil)).Elem()
}

func (i SystemAutoupdateScheduleMap) ToSystemAutoupdateScheduleMapOutput() SystemAutoupdateScheduleMapOutput {
	return i.ToSystemAutoupdateScheduleMapOutputWithContext(context.Background())
}

func (i SystemAutoupdateScheduleMap) ToSystemAutoupdateScheduleMapOutputWithContext(ctx context.Context) SystemAutoupdateScheduleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemAutoupdateScheduleMapOutput)
}

type SystemAutoupdateScheduleOutput struct{ *pulumi.OutputState }

func (SystemAutoupdateScheduleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemAutoupdateSchedule)(nil)).Elem()
}

func (o SystemAutoupdateScheduleOutput) ToSystemAutoupdateScheduleOutput() SystemAutoupdateScheduleOutput {
	return o
}

func (o SystemAutoupdateScheduleOutput) ToSystemAutoupdateScheduleOutputWithContext(ctx context.Context) SystemAutoupdateScheduleOutput {
	return o
}

func (o SystemAutoupdateScheduleOutput) Day() pulumi.StringOutput {
	return o.ApplyT(func(v *SystemAutoupdateSchedule) pulumi.StringOutput { return v.Day }).(pulumi.StringOutput)
}

func (o SystemAutoupdateScheduleOutput) Frequency() pulumi.StringOutput {
	return o.ApplyT(func(v *SystemAutoupdateSchedule) pulumi.StringOutput { return v.Frequency }).(pulumi.StringOutput)
}

func (o SystemAutoupdateScheduleOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *SystemAutoupdateSchedule) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o SystemAutoupdateScheduleOutput) Time() pulumi.StringOutput {
	return o.ApplyT(func(v *SystemAutoupdateSchedule) pulumi.StringOutput { return v.Time }).(pulumi.StringOutput)
}

func (o SystemAutoupdateScheduleOutput) Vdomparam() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SystemAutoupdateSchedule) pulumi.StringPtrOutput { return v.Vdomparam }).(pulumi.StringPtrOutput)
}

type SystemAutoupdateScheduleArrayOutput struct{ *pulumi.OutputState }

func (SystemAutoupdateScheduleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SystemAutoupdateSchedule)(nil)).Elem()
}

func (o SystemAutoupdateScheduleArrayOutput) ToSystemAutoupdateScheduleArrayOutput() SystemAutoupdateScheduleArrayOutput {
	return o
}

func (o SystemAutoupdateScheduleArrayOutput) ToSystemAutoupdateScheduleArrayOutputWithContext(ctx context.Context) SystemAutoupdateScheduleArrayOutput {
	return o
}

func (o SystemAutoupdateScheduleArrayOutput) Index(i pulumi.IntInput) SystemAutoupdateScheduleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SystemAutoupdateSchedule {
		return vs[0].([]*SystemAutoupdateSchedule)[vs[1].(int)]
	}).(SystemAutoupdateScheduleOutput)
}

type SystemAutoupdateScheduleMapOutput struct{ *pulumi.OutputState }

func (SystemAutoupdateScheduleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SystemAutoupdateSchedule)(nil)).Elem()
}

func (o SystemAutoupdateScheduleMapOutput) ToSystemAutoupdateScheduleMapOutput() SystemAutoupdateScheduleMapOutput {
	return o
}

func (o SystemAutoupdateScheduleMapOutput) ToSystemAutoupdateScheduleMapOutputWithContext(ctx context.Context) SystemAutoupdateScheduleMapOutput {
	return o
}

func (o SystemAutoupdateScheduleMapOutput) MapIndex(k pulumi.StringInput) SystemAutoupdateScheduleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SystemAutoupdateSchedule {
		return vs[0].(map[string]*SystemAutoupdateSchedule)[vs[1].(string)]
	}).(SystemAutoupdateScheduleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SystemAutoupdateScheduleInput)(nil)).Elem(), &SystemAutoupdateSchedule{})
	pulumi.RegisterInputType(reflect.TypeOf((*SystemAutoupdateScheduleArrayInput)(nil)).Elem(), SystemAutoupdateScheduleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SystemAutoupdateScheduleMapInput)(nil)).Elem(), SystemAutoupdateScheduleMap{})
	pulumi.RegisterOutputType(SystemAutoupdateScheduleOutput{})
	pulumi.RegisterOutputType(SystemAutoupdateScheduleArrayOutput{})
	pulumi.RegisterOutputType(SystemAutoupdateScheduleMapOutput{})
}
