// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Configure web proxy tunnelling for the FDN.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-fortios/sdk/go/fortios"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := fortios.NewSystemAutoupdateTunneling(ctx, "trname", &fortios.SystemAutoupdateTunnelingArgs{
// 			Port:   pulumi.Int(0),
// 			Status: pulumi.String("disable"),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// SystemAutoupdate Tunneling can be imported using any of these accepted formats$ export "FORTIOS_IMPORT_TABLE"="true"
//
// ```sh
//  $ pulumi import fortios:index/systemAutoupdateTunneling:SystemAutoupdateTunneling labelname SystemAutoupdateTunneling
// ```
//
//  $ unset "FORTIOS_IMPORT_TABLE"
type SystemAutoupdateTunneling struct {
	pulumi.CustomResourceState

	// Web proxy IP address or FQDN.
	Address pulumi.StringOutput `pulumi:"address"`
	// Web proxy password.
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// Web proxy port.
	Port pulumi.IntOutput `pulumi:"port"`
	// Enable/disable web proxy tunnelling. Valid values: `enable`, `disable`.
	Status pulumi.StringOutput `pulumi:"status"`
	// Web proxy username.
	Username pulumi.StringOutput `pulumi:"username"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrOutput `pulumi:"vdomparam"`
}

// NewSystemAutoupdateTunneling registers a new resource with the given unique name, arguments, and options.
func NewSystemAutoupdateTunneling(ctx *pulumi.Context,
	name string, args *SystemAutoupdateTunnelingArgs, opts ...pulumi.ResourceOption) (*SystemAutoupdateTunneling, error) {
	if args == nil {
		args = &SystemAutoupdateTunnelingArgs{}
	}

	var resource SystemAutoupdateTunneling
	err := ctx.RegisterResource("fortios:index/systemAutoupdateTunneling:SystemAutoupdateTunneling", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSystemAutoupdateTunneling gets an existing SystemAutoupdateTunneling resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSystemAutoupdateTunneling(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SystemAutoupdateTunnelingState, opts ...pulumi.ResourceOption) (*SystemAutoupdateTunneling, error) {
	var resource SystemAutoupdateTunneling
	err := ctx.ReadResource("fortios:index/systemAutoupdateTunneling:SystemAutoupdateTunneling", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SystemAutoupdateTunneling resources.
type systemAutoupdateTunnelingState struct {
	// Web proxy IP address or FQDN.
	Address *string `pulumi:"address"`
	// Web proxy password.
	Password *string `pulumi:"password"`
	// Web proxy port.
	Port *int `pulumi:"port"`
	// Enable/disable web proxy tunnelling. Valid values: `enable`, `disable`.
	Status *string `pulumi:"status"`
	// Web proxy username.
	Username *string `pulumi:"username"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

type SystemAutoupdateTunnelingState struct {
	// Web proxy IP address or FQDN.
	Address pulumi.StringPtrInput
	// Web proxy password.
	Password pulumi.StringPtrInput
	// Web proxy port.
	Port pulumi.IntPtrInput
	// Enable/disable web proxy tunnelling. Valid values: `enable`, `disable`.
	Status pulumi.StringPtrInput
	// Web proxy username.
	Username pulumi.StringPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (SystemAutoupdateTunnelingState) ElementType() reflect.Type {
	return reflect.TypeOf((*systemAutoupdateTunnelingState)(nil)).Elem()
}

type systemAutoupdateTunnelingArgs struct {
	// Web proxy IP address or FQDN.
	Address *string `pulumi:"address"`
	// Web proxy password.
	Password *string `pulumi:"password"`
	// Web proxy port.
	Port *int `pulumi:"port"`
	// Enable/disable web proxy tunnelling. Valid values: `enable`, `disable`.
	Status *string `pulumi:"status"`
	// Web proxy username.
	Username *string `pulumi:"username"`
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

// The set of arguments for constructing a SystemAutoupdateTunneling resource.
type SystemAutoupdateTunnelingArgs struct {
	// Web proxy IP address or FQDN.
	Address pulumi.StringPtrInput
	// Web proxy password.
	Password pulumi.StringPtrInput
	// Web proxy port.
	Port pulumi.IntPtrInput
	// Enable/disable web proxy tunnelling. Valid values: `enable`, `disable`.
	Status pulumi.StringPtrInput
	// Web proxy username.
	Username pulumi.StringPtrInput
	// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput
}

func (SystemAutoupdateTunnelingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*systemAutoupdateTunnelingArgs)(nil)).Elem()
}

type SystemAutoupdateTunnelingInput interface {
	pulumi.Input

	ToSystemAutoupdateTunnelingOutput() SystemAutoupdateTunnelingOutput
	ToSystemAutoupdateTunnelingOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingOutput
}

func (*SystemAutoupdateTunneling) ElementType() reflect.Type {
	return reflect.TypeOf((*SystemAutoupdateTunneling)(nil))
}

func (i *SystemAutoupdateTunneling) ToSystemAutoupdateTunnelingOutput() SystemAutoupdateTunnelingOutput {
	return i.ToSystemAutoupdateTunnelingOutputWithContext(context.Background())
}

func (i *SystemAutoupdateTunneling) ToSystemAutoupdateTunnelingOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemAutoupdateTunnelingOutput)
}

func (i *SystemAutoupdateTunneling) ToSystemAutoupdateTunnelingPtrOutput() SystemAutoupdateTunnelingPtrOutput {
	return i.ToSystemAutoupdateTunnelingPtrOutputWithContext(context.Background())
}

func (i *SystemAutoupdateTunneling) ToSystemAutoupdateTunnelingPtrOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemAutoupdateTunnelingPtrOutput)
}

type SystemAutoupdateTunnelingPtrInput interface {
	pulumi.Input

	ToSystemAutoupdateTunnelingPtrOutput() SystemAutoupdateTunnelingPtrOutput
	ToSystemAutoupdateTunnelingPtrOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingPtrOutput
}

type systemAutoupdateTunnelingPtrType SystemAutoupdateTunnelingArgs

func (*systemAutoupdateTunnelingPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemAutoupdateTunneling)(nil))
}

func (i *systemAutoupdateTunnelingPtrType) ToSystemAutoupdateTunnelingPtrOutput() SystemAutoupdateTunnelingPtrOutput {
	return i.ToSystemAutoupdateTunnelingPtrOutputWithContext(context.Background())
}

func (i *systemAutoupdateTunnelingPtrType) ToSystemAutoupdateTunnelingPtrOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemAutoupdateTunnelingPtrOutput)
}

// SystemAutoupdateTunnelingArrayInput is an input type that accepts SystemAutoupdateTunnelingArray and SystemAutoupdateTunnelingArrayOutput values.
// You can construct a concrete instance of `SystemAutoupdateTunnelingArrayInput` via:
//
//          SystemAutoupdateTunnelingArray{ SystemAutoupdateTunnelingArgs{...} }
type SystemAutoupdateTunnelingArrayInput interface {
	pulumi.Input

	ToSystemAutoupdateTunnelingArrayOutput() SystemAutoupdateTunnelingArrayOutput
	ToSystemAutoupdateTunnelingArrayOutputWithContext(context.Context) SystemAutoupdateTunnelingArrayOutput
}

type SystemAutoupdateTunnelingArray []SystemAutoupdateTunnelingInput

func (SystemAutoupdateTunnelingArray) ElementType() reflect.Type {
	return reflect.TypeOf(([]*SystemAutoupdateTunneling)(nil))
}

func (i SystemAutoupdateTunnelingArray) ToSystemAutoupdateTunnelingArrayOutput() SystemAutoupdateTunnelingArrayOutput {
	return i.ToSystemAutoupdateTunnelingArrayOutputWithContext(context.Background())
}

func (i SystemAutoupdateTunnelingArray) ToSystemAutoupdateTunnelingArrayOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemAutoupdateTunnelingArrayOutput)
}

// SystemAutoupdateTunnelingMapInput is an input type that accepts SystemAutoupdateTunnelingMap and SystemAutoupdateTunnelingMapOutput values.
// You can construct a concrete instance of `SystemAutoupdateTunnelingMapInput` via:
//
//          SystemAutoupdateTunnelingMap{ "key": SystemAutoupdateTunnelingArgs{...} }
type SystemAutoupdateTunnelingMapInput interface {
	pulumi.Input

	ToSystemAutoupdateTunnelingMapOutput() SystemAutoupdateTunnelingMapOutput
	ToSystemAutoupdateTunnelingMapOutputWithContext(context.Context) SystemAutoupdateTunnelingMapOutput
}

type SystemAutoupdateTunnelingMap map[string]SystemAutoupdateTunnelingInput

func (SystemAutoupdateTunnelingMap) ElementType() reflect.Type {
	return reflect.TypeOf((map[string]*SystemAutoupdateTunneling)(nil))
}

func (i SystemAutoupdateTunnelingMap) ToSystemAutoupdateTunnelingMapOutput() SystemAutoupdateTunnelingMapOutput {
	return i.ToSystemAutoupdateTunnelingMapOutputWithContext(context.Background())
}

func (i SystemAutoupdateTunnelingMap) ToSystemAutoupdateTunnelingMapOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemAutoupdateTunnelingMapOutput)
}

type SystemAutoupdateTunnelingOutput struct {
	*pulumi.OutputState
}

func (SystemAutoupdateTunnelingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SystemAutoupdateTunneling)(nil))
}

func (o SystemAutoupdateTunnelingOutput) ToSystemAutoupdateTunnelingOutput() SystemAutoupdateTunnelingOutput {
	return o
}

func (o SystemAutoupdateTunnelingOutput) ToSystemAutoupdateTunnelingOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingOutput {
	return o
}

func (o SystemAutoupdateTunnelingOutput) ToSystemAutoupdateTunnelingPtrOutput() SystemAutoupdateTunnelingPtrOutput {
	return o.ToSystemAutoupdateTunnelingPtrOutputWithContext(context.Background())
}

func (o SystemAutoupdateTunnelingOutput) ToSystemAutoupdateTunnelingPtrOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingPtrOutput {
	return o.ApplyT(func(v SystemAutoupdateTunneling) *SystemAutoupdateTunneling {
		return &v
	}).(SystemAutoupdateTunnelingPtrOutput)
}

type SystemAutoupdateTunnelingPtrOutput struct {
	*pulumi.OutputState
}

func (SystemAutoupdateTunnelingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemAutoupdateTunneling)(nil))
}

func (o SystemAutoupdateTunnelingPtrOutput) ToSystemAutoupdateTunnelingPtrOutput() SystemAutoupdateTunnelingPtrOutput {
	return o
}

func (o SystemAutoupdateTunnelingPtrOutput) ToSystemAutoupdateTunnelingPtrOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingPtrOutput {
	return o
}

type SystemAutoupdateTunnelingArrayOutput struct{ *pulumi.OutputState }

func (SystemAutoupdateTunnelingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SystemAutoupdateTunneling)(nil))
}

func (o SystemAutoupdateTunnelingArrayOutput) ToSystemAutoupdateTunnelingArrayOutput() SystemAutoupdateTunnelingArrayOutput {
	return o
}

func (o SystemAutoupdateTunnelingArrayOutput) ToSystemAutoupdateTunnelingArrayOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingArrayOutput {
	return o
}

func (o SystemAutoupdateTunnelingArrayOutput) Index(i pulumi.IntInput) SystemAutoupdateTunnelingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) SystemAutoupdateTunneling {
		return vs[0].([]SystemAutoupdateTunneling)[vs[1].(int)]
	}).(SystemAutoupdateTunnelingOutput)
}

type SystemAutoupdateTunnelingMapOutput struct{ *pulumi.OutputState }

func (SystemAutoupdateTunnelingMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]SystemAutoupdateTunneling)(nil))
}

func (o SystemAutoupdateTunnelingMapOutput) ToSystemAutoupdateTunnelingMapOutput() SystemAutoupdateTunnelingMapOutput {
	return o
}

func (o SystemAutoupdateTunnelingMapOutput) ToSystemAutoupdateTunnelingMapOutputWithContext(ctx context.Context) SystemAutoupdateTunnelingMapOutput {
	return o
}

func (o SystemAutoupdateTunnelingMapOutput) MapIndex(k pulumi.StringInput) SystemAutoupdateTunnelingOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) SystemAutoupdateTunneling {
		return vs[0].(map[string]SystemAutoupdateTunneling)[vs[1].(string)]
	}).(SystemAutoupdateTunnelingOutput)
}

func init() {
	pulumi.RegisterOutputType(SystemAutoupdateTunnelingOutput{})
	pulumi.RegisterOutputType(SystemAutoupdateTunnelingPtrOutput{})
	pulumi.RegisterOutputType(SystemAutoupdateTunnelingArrayOutput{})
	pulumi.RegisterOutputType(SystemAutoupdateTunnelingMapOutput{})
}
