jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: 1 day
        skip-tags: false
        skip-recent: 2

name: cleanup
"on":
  schedule:
  - cron: 0 1 * * *
