// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Use this data source to get information on an fortios router communitylist
 */
export function getRouterCommunityList(args: GetRouterCommunityListArgs, opts?: pulumi.InvokeOptions): Promise<GetRouterCommunityListResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("fortios:index/getRouterCommunityList:GetRouterCommunityList", {
        "name": args.name,
        "vdomparam": args.vdomparam,
    }, opts);
}

/**
 * A collection of arguments for invoking GetRouterCommunityList.
 */
export interface GetRouterCommunityListArgs {
    /**
     * Specify the name of the desired router communitylist.
     */
    name: string;
    /**
     * Specifies the vdom to which the data source will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
     */
    vdomparam?: string;
}

/**
 * A collection of values returned by GetRouterCommunityList.
 */
export interface GetRouterCommunityListResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Community list name.
     */
    readonly name: string;
    /**
     * Community list rule. The structure of `rule` block is documented below.
     */
    readonly rules: outputs.GetRouterCommunityListRule[];
    /**
     * Community list type (standard or expanded).
     */
    readonly type: string;
    readonly vdomparam?: string;
}
