// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Configure WTP groups.
 *
 * ## Import
 *
 * WirelessController WtpGroup can be imported using any of these accepted formats$ export "FORTIOS_IMPORT_TABLE"="true"
 *
 * ```sh
 *  $ pulumi import fortios:index/wirelessControllerWtpGroup:WirelessControllerWtpGroup labelname {{name}}
 * ```
 *
 *  $ unset "FORTIOS_IMPORT_TABLE"
 */
export class WirelessControllerWtpGroup extends pulumi.CustomResource {
    /**
     * Get an existing WirelessControllerWtpGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WirelessControllerWtpGroupState, opts?: pulumi.CustomResourceOptions): WirelessControllerWtpGroup {
        return new WirelessControllerWtpGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fortios:index/wirelessControllerWtpGroup:WirelessControllerWtpGroup';

    /**
     * Returns true if the given object is an instance of WirelessControllerWtpGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WirelessControllerWtpGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WirelessControllerWtpGroup.__pulumiType;
    }

    /**
     * true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
     */
    public readonly dynamicSortSubtable!: pulumi.Output<string | undefined>;
    /**
     * WTP group name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * FortiAP models to define the WTP group platform type.
     */
    public readonly platformType!: pulumi.Output<string>;
    /**
     * Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
     */
    public readonly vdomparam!: pulumi.Output<string | undefined>;
    /**
     * WTP list. The structure of `wtps` block is documented below.
     */
    public readonly wtps!: pulumi.Output<outputs.WirelessControllerWtpGroupWtp[] | undefined>;

    /**
     * Create a WirelessControllerWtpGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WirelessControllerWtpGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WirelessControllerWtpGroupArgs | WirelessControllerWtpGroupState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WirelessControllerWtpGroupState | undefined;
            inputs["dynamicSortSubtable"] = state ? state.dynamicSortSubtable : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["platformType"] = state ? state.platformType : undefined;
            inputs["vdomparam"] = state ? state.vdomparam : undefined;
            inputs["wtps"] = state ? state.wtps : undefined;
        } else {
            const args = argsOrState as WirelessControllerWtpGroupArgs | undefined;
            inputs["dynamicSortSubtable"] = args ? args.dynamicSortSubtable : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["platformType"] = args ? args.platformType : undefined;
            inputs["vdomparam"] = args ? args.vdomparam : undefined;
            inputs["wtps"] = args ? args.wtps : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(WirelessControllerWtpGroup.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering WirelessControllerWtpGroup resources.
 */
export interface WirelessControllerWtpGroupState {
    /**
     * true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
     */
    dynamicSortSubtable?: pulumi.Input<string>;
    /**
     * WTP group name.
     */
    name?: pulumi.Input<string>;
    /**
     * FortiAP models to define the WTP group platform type.
     */
    platformType?: pulumi.Input<string>;
    /**
     * Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
     */
    vdomparam?: pulumi.Input<string>;
    /**
     * WTP list. The structure of `wtps` block is documented below.
     */
    wtps?: pulumi.Input<pulumi.Input<inputs.WirelessControllerWtpGroupWtp>[]>;
}

/**
 * The set of arguments for constructing a WirelessControllerWtpGroup resource.
 */
export interface WirelessControllerWtpGroupArgs {
    /**
     * true or false, set this parameter to true when using dynamic forEach + toset to configure and sort sub-tables, please do not set this parameter when configuring static sub-tables.
     */
    dynamicSortSubtable?: pulumi.Input<string>;
    /**
     * WTP group name.
     */
    name?: pulumi.Input<string>;
    /**
     * FortiAP models to define the WTP group platform type.
     */
    platformType?: pulumi.Input<string>;
    /**
     * Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
     */
    vdomparam?: pulumi.Input<string>;
    /**
     * WTP list. The structure of `wtps` block is documented below.
     */
    wtps?: pulumi.Input<pulumi.Input<inputs.WirelessControllerWtpGroupWtp>[]>;
}
